/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProgressReport.java
 *
 * Created on Sep 27, 2011, 3:36:08 PM
 */
package edu.uncc.bioinformatics.quickloadbuilder;

import javax.swing.JProgressBar;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.ResourceMap;

/**
 *
 * @author jfvillal
 */
public class ProgressReport extends javax.swing.JPanel {
    QuickLoadArchiveBuilderView Parent;
    
    /** Creates new form ProgressReport */
    public ProgressReport(QuickLoadArchiveBuilderView parent ) {
        ResourceMap resourceMap = parent.getResourceMap();
        initComponents();
        
        CurrentTask.setMaximum(100);
        this.GeneralProgress.setMaximum(100);
        
        Logo.setIcon( resourceMap.getIcon( "WelcomeIcon" ) );
        Parent = parent;
    }
    
    public void setSuccess( boolean success){
        if( success ){
            String str = "";
            if( Parent.CreateQuickloadArchive ){
                str = "created";
            }else{
                str = "updated";
            }
            Message.setText("The Quickload archive was successfully " + str + ".");
        }else{
            Message.setText("The process was aborted!");
            GeneralProgress.setVisible(false);
            Status.setVisible(false);
        }
    }
    
    public void setCurrentTaskProgress( int i ){
        this.CurrentTask.setValue(i);
    }
    
    public void setGeneralProgress( int i ){
        this.GeneralProgress.setValue( i );
    }
    
    public void setCurrentTaskText( String message){
        this.Status.setText( message );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        Message = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        GeneralProgress = new javax.swing.JProgressBar();
        Status = new javax.swing.JLabel();
        CurrentTask = new javax.swing.JProgressBar();
        message = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        Logo.setName("Logo"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edu.uncc.bioinformatics.quickloadbuilder.QuickLoadArchiveBuilderApp.class).getContext().getResourceMap(ProgressReport.class);
        Message.setText(resourceMap.getString("Message.text")); // NOI18N
        Message.setName("Message"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        GeneralProgress.setValue(50);
        GeneralProgress.setName("GeneralProgress"); // NOI18N

        Status.setText(resourceMap.getString("Status.text")); // NOI18N
        Status.setName("Status"); // NOI18N

        CurrentTask.setValue(60);
        CurrentTask.setName("CurrentTask"); // NOI18N

        message.setText(resourceMap.getString("message.text")); // NOI18N
        message.setName("message"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Message, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addComponent(Status)
                    .addComponent(GeneralProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addComponent(CurrentTask, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addComponent(message)
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addGap(73, 73, 73)
                        .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(message)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CurrentTask, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GeneralProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Status)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar CurrentTask;
    private javax.swing.JProgressBar GeneralProgress;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Message;
    private javax.swing.JLabel Status;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
