package com.affymetrix.igb.trackAdjuster;

import com.affymetrix.common.CommonUtils;
import com.affymetrix.genometryImpl.style.ITrackStyleExtended;
import com.affymetrix.genoviz.swing.CustomTitleBorder;
import com.affymetrix.genoviz.swing.MenuUtil;
import com.affymetrix.igb.osgi.service.IGBService;
import com.affymetrix.igb.osgi.service.IGBTabPanel;
import com.affymetrix.igb.shared.CollapseExpandAction;
import com.affymetrix.igb.shared.RepackTiersAction;
import com.affymetrix.igb.shared.TierGlyph;
import com.affymetrix.igb.trackAdjuster.TrackAdjusterTab.DisplayType;
import java.awt.Cursor;
import java.awt.Rectangle;
import java.util.List;
import java.util.ResourceBundle;

public class TrackAdjusterTabGUI extends IGBTabPanel {

	private static final long serialVersionUID = 1L;
	public static final ResourceBundle BUNDLE = ResourceBundle.getBundle("trackAdjuster");
	private static final int TAB_POSITION = 3;
	public TrackAdjusterTab sgt;
	private static TrackAdjusterTabGUI singleton;
	private RepackTiersAction repackStub;
	static final Cursor defaultCursor, openHandCursor, closedHandCursor;

	static {
		defaultCursor = new Cursor(Cursor.DEFAULT_CURSOR);
		openHandCursor = new Cursor(Cursor.HAND_CURSOR);
		closedHandCursor = new Cursor(Cursor.HAND_CURSOR);
	}

	/**
	 * Creates new form SimpleGraphTab1
	 */
	public TrackAdjusterTabGUI(IGBService _igbService) {
		super(_igbService, BUNDLE.getString("trackAdjusterTab"), BUNDLE.getString("trackAdjusterTab"), false, TAB_POSITION);
		TrackAdjusterTab.init(igbService);
		sgt = TrackAdjusterTab.getSingleton();
		repackStub = new RepackTiersAction(null, null, null) {

			private static final long serialVersionUID = 1L;
		};
		initComponents();
	}

	public static void init(IGBService igbService) {
		singleton = new TrackAdjusterTabGUI(igbService);
	}

	public static synchronized TrackAdjusterTabGUI getSingleton() {
		return singleton;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stylegroup = sgt.stylegroup;
        DisplayModeButtonGroup = new javax.swing.ButtonGroup();
        VisibleRangeButtonGroup = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        DisplayButtonGroup = new javax.swing.ButtonGroup();
        StylePanel = new javax.swing.JPanel();
        fgLabel = new javax.swing.JLabel();
        fgColorComboBox = sgt.fgColorComboBox;
        bgLabel = new javax.swing.JLabel();
        bgColorComboBox = sgt.bgColorComboBox;
        nameSizeComboBox = sgt.trackNameSizeComboBox;
        jLabel3 = new javax.swing.JLabel();
        colorSchemeChooser = sgt.colorSchemeBox;
        AnnotationPanel = sgt.annotationPanel;
        jLabel6 = new javax.swing.JLabel();
        maxStackDepthTextField = sgt.maxStackDepthTextField;
        fitViewButton = new javax.swing.JButton();
        collapseButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        graphPanel = new javax.swing.JPanel();
        barB = sgt.barB;
        lineB = sgt.lineB;
        mmavgB = sgt.mmavgB;
        dotB = sgt.dotB;
        PluginRadioButton = sgt.graphPluginB;
        PluginComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        labelCB = sgt.labelCB;
        yaxisCB = sgt.yaxisCB;
        RangePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        by_valRB_val = sgt.vis_bounds_setter.by_valRB;
        by_percentileRB_val = sgt.vis_bounds_setter.by_percentileRB;
        rangeSlider = sgt.vis_bounds_setter.ValueSlider;
        minValLabel = new javax.swing.JLabel();
        minText = sgt.vis_bounds_setter.min_valT;
        maxText = sgt.vis_bounds_setter.max_valT;
        maxValLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pluginPrefButton = new javax.swing.JButton();
        PluginButton = sgt.pluginB;
        jLabel5 = new javax.swing.JLabel();
        AnnotationButton = sgt.annotationB;
        AutoButton = sgt.autoB;
        jComboBox2 = new javax.swing.JComboBox();
        GraphButton = sgt.graphB;
        floatingCheckBox = sgt.floatCB;
        TopPanel = new javax.swing.JPanel();
        height_slider = sgt.height_slider;
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        selectAllB = new javax.swing.JButton();
        trackNameTextField = sgt.trackName;

        jMenu1.setText("jMenu1");

        StylePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Track Style"));
        StylePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StylePanelMouseClicked(evt);
            }
        });
        StylePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                StylePanelMouseMoved(evt);
            }
        });

        fgLabel.setText("Foreground:");

        fgColorComboBox.setBackground(new java.awt.Color(255, 255, 255));
        fgColorComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        fgColorComboBox.setButtonVisible(false);
        fgColorComboBox.setColorValueVisible(false);
        fgColorComboBox.setMaximumSize(new java.awt.Dimension(150, 20));
        fgColorComboBox.setStretchToFit(true);
        fgColorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fgColorComboBoxActionPerformed(evt);
            }
        });

        bgLabel.setText("Background:");

        bgColorComboBox.setBackground(new java.awt.Color(255, 255, 255));
        bgColorComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        bgColorComboBox.setButtonVisible(false);
        bgColorComboBox.setColorValueVisible(false);
        bgColorComboBox.setMaximumSize(new java.awt.Dimension(150, 20));
        bgColorComboBox.setStretchToFit(true);
        bgColorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgColorComboBoxActionPerformed(evt);
            }
        });

        nameSizeComboBox.setModel(sgt.trackNameSizeComboBox.getModel());
        nameSizeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSizeComboBoxtrackNameSizeComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Name Size:");

        org.jdesktop.layout.GroupLayout StylePanelLayout = new org.jdesktop.layout.GroupLayout(StylePanel);
        StylePanel.setLayout(StylePanelLayout);
        StylePanelLayout.setHorizontalGroup(
            StylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(StylePanelLayout.createSequentialGroup()
                .add(5, 5, 5)
                .add(StylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(StylePanelLayout.createSequentialGroup()
                        .add(StylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(bgLabel)
                            .add(fgLabel))
                        .add(5, 5, 5)
                        .add(StylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(bgColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(fgColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(StylePanelLayout.createSequentialGroup()
                        .add(jLabel3)
                        .add(5, 5, 5)
                        .add(nameSizeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 68, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .add(StylePanelLayout.createSequentialGroup()
                .add(colorSchemeChooser, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        StylePanelLayout.setVerticalGroup(
            StylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(StylePanelLayout.createSequentialGroup()
                .add(StylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bgLabel)
                    .add(bgColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(10, 10, 10)
                .add(StylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(fgColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(fgLabel))
                .add(8, 8, 8)
                .add(StylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nameSizeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .add(8, 8, 8)
                .add(colorSchemeChooser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AnnotationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Annotation")));
        AnnotationPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnnotationPanelMouseClicked(evt);
            }
        });
        AnnotationPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AnnotationPanelMouseMoved(evt);
            }
        });

        jLabel6.setText("Stack Depth: ");

        maxStackDepthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxStackDepthTextFieldActionPerformed(evt);
            }
        });

        fitViewButton.setText("Fit View");
        fitViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fitViewButtonActionPerformed(evt);
            }
        });

        collapseButton.setText("Collapse");
        collapseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collapseButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Apply");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout AnnotationPanelLayout = new org.jdesktop.layout.GroupLayout(AnnotationPanel);
        AnnotationPanel.setLayout(AnnotationPanelLayout);
        AnnotationPanelLayout.setHorizontalGroup(
            AnnotationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
            .add(AnnotationPanelLayout.createSequentialGroup()
                .add(5, 5, 5)
                .add(AnnotationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(AnnotationPanelLayout.createSequentialGroup()
                        .add(jLabel6)
                        .add(0, 0, 0)
                        .add(maxStackDepthTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, 0)
                        .add(jButton2))
                    .add(AnnotationPanelLayout.createSequentialGroup()
                        .add(fitViewButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(5, 5, 5)
                        .add(collapseButton)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AnnotationPanelLayout.linkSize(new java.awt.Component[] {collapseButton, fitViewButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        AnnotationPanelLayout.setVerticalGroup(
            AnnotationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(AnnotationPanelLayout.createSequentialGroup()
                .add(AnnotationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(jLabel6)
                    .add(maxStackDepthTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton2))
                .add(10, 10, 10)
                .add(AnnotationPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(collapseButton)
                    .add(fitViewButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        graphPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Graph"));
        graphPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                graphPanelMouseClicked(evt);
            }
        });
        graphPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                graphPanelMouseMoved(evt);
            }
        });

        barB.setText("Bar");

        lineB.setText("Line");

        mmavgB.setText("Min/Max/Avg");

        dotB.setText("Dot");

        stylegroup.add(PluginRadioButton);

        PluginComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HeatMap" }));
        PluginComboBox.setFocusCycleRoot(true);

        jLabel7.setText("Show:");

        labelCB.setText("Label");

        yaxisCB.setText("Y Axis");

        org.jdesktop.layout.GroupLayout graphPanelLayout = new org.jdesktop.layout.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(graphPanelLayout.createSequentialGroup()
                .add(5, 5, 5)
                .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(graphPanelLayout.createSequentialGroup()
                        .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(barB)
                            .add(dotB)
                            .add(PluginRadioButton))
                        .add(0, 0, 0)
                        .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(mmavgB)
                            .add(lineB)
                            .add(PluginComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(graphPanelLayout.createSequentialGroup()
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(labelCB)
                        .add(0, 0, 0)
                        .add(yaxisCB)))
                .addContainerGap())
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(graphPanelLayout.createSequentialGroup()
                .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(labelCB)
                    .add(yaxisCB)
                    .add(jLabel7))
                .add(5, 5, 5)
                .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(barB)
                    .add(lineB))
                .add(5, 5, 5)
                .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(dotB)
                    .add(mmavgB))
                .add(5, 5, 5)
                .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PluginRadioButton)
                    .add(PluginComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        RangePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Y Axis Scale (Graph)"));
        RangePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RangePanelMouseClicked(evt);
            }
        });
        RangePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                RangePanelMouseMoved(evt);
            }
        });

        jLabel2.setText("Set By:");

        VisibleRangeButtonGroup.add(by_valRB_val);
        by_valRB_val.setSelected(true);
        by_valRB_val.setText("Value");
        by_valRB_val.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                by_valRB_valActionPerformed(evt);
            }
        });

        VisibleRangeButtonGroup.add(by_percentileRB_val);
        by_percentileRB_val.setText("Percentile");
        by_percentileRB_val.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                by_percentileRB_valActionPerformed(evt);
            }
        });

        rangeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rangeSliderStateChanged(evt);
            }
        });

        minValLabel.setText("Min:");

        minText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minTextActionPerformed(evt);
            }
        });

        maxText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxTextActionPerformed(evt);
            }
        });

        maxValLabel.setText("Max:");

        org.jdesktop.layout.GroupLayout RangePanelLayout = new org.jdesktop.layout.GroupLayout(RangePanel);
        RangePanel.setLayout(RangePanelLayout);
        RangePanelLayout.setHorizontalGroup(
            RangePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(RangePanelLayout.createSequentialGroup()
                .add(5, 5, 5)
                .add(RangePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(RangePanelLayout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(rangeSlider, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(10, 10, 10))
                    .add(RangePanelLayout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(by_valRB_val)
                        .add(0, 0, 0)
                        .add(by_percentileRB_val)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, RangePanelLayout.createSequentialGroup()
                        .add(minValLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(minText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(maxValLabel)
                        .add(5, 5, 5)
                        .add(maxText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(4, 4, 4))))
        );

        RangePanelLayout.linkSize(new java.awt.Component[] {maxText, minText}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        RangePanelLayout.setVerticalGroup(
            RangePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, RangePanelLayout.createSequentialGroup()
                .add(RangePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(jLabel2)
                    .add(by_valRB_val)
                    .add(by_percentileRB_val))
                .add(10, 10, 10)
                .add(rangeSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(10, 10, 10)
                .add(RangePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(maxText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(maxValLabel)
                    .add(minValLabel)
                    .add(minText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        RangePanelLayout.linkSize(new java.awt.Component[] {maxText, minText}, org.jdesktop.layout.GroupLayout.VERTICAL);

        pluginPrefButton.setIcon(CommonUtils.getInstance().getIcon("images/configure.png"));
        pluginPrefButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pluginPrefButtonActionPerformed(evt);
            }
        });

        DisplayButtonGroup.add(PluginButton);
        PluginButton.setEnabled(false);
        PluginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PluginButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Display As:");

        DisplayButtonGroup.add(AnnotationButton);
        AnnotationButton.setText("Annotation");
        AnnotationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnotationButtonActionPerformed(evt);
            }
        });

        DisplayButtonGroup.add(AutoButton);
        AutoButton.setText("Auto");
        AutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoButtonActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Plugin" }));
        jComboBox2.setEnabled(false);

        DisplayButtonGroup.add(GraphButton);
        GraphButton.setText("Graph");
        GraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphButtonActionPerformed(evt);
            }
        });

        floatingCheckBox.setText("Floating");
        floatingCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floatingCheckBoxActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(3, 3, 3)
                .add(jLabel5)
                .add(5, 5, 5)
                .add(AnnotationButton)
                .add(5, 5, 5)
                .add(GraphButton)
                .add(10, 10, 10)
                .add(AutoButton)
                .add(10, 10, 10)
                .add(PluginButton)
                .add(5, 5, 5)
                .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(pluginPrefButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(floatingCheckBox)
                .addContainerGap(0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                .add(jLabel5)
                .add(AnnotationButton)
                .add(GraphButton)
                .add(AutoButton)
                .add(PluginButton)
                .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(pluginPrefButton)
                .add(floatingCheckBox))
        );

        //This allows the Bundle String to be applied,
        //and also the String to appear in the GUI during design.
        AnnotationButton.setText(sgt.annotationB.getText());
        AutoButton.setText(sgt.autoB.getText());
        GraphButton.setText(sgt.graphB.getText());

        height_slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                height_sliderStateChanged(evt);
            }
        });

        jLabel8.setText("Track Name:");

        jLabel1.setText("Height:");

        selectAllB.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        selectAllB.setText("Select All   ");
        selectAllB.setFocusable(false);
        selectAllB.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        selectAllB.setIcon(MenuUtil.getIcon("images/arrow_down.png"));
        selectAllB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectAllBMouseClicked(evt);
            }
        });

        trackNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackNameTextFieldActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout TopPanelLayout = new org.jdesktop.layout.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(TopPanelLayout.createSequentialGroup()
                .add(selectAllB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 156, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel8)
                .add(5, 5, 5)
                .add(trackNameTextField)
                .add(5, 5, 5)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(height_slider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 255, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(TopPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                .add(height_slider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel1)
                .add(selectAllB)
                .add(jLabel8)
                .add(trackNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(TopPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(StylePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 159, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(3, 3, 3)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(AnnotationPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 239, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(3, 3, 3)
                        .add(graphPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 196, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(3, 3, 3)
                        .add(RangePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(TopPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, 0)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, AnnotationPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, graphPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(RangePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(StylePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(new java.awt.Component[] {AnnotationPanel, RangePanel, graphPanel}, org.jdesktop.layout.GroupLayout.VERTICAL);

        StylePanel.setBorder(new CustomTitleBorder("Style -", "Configure"));
        AnnotationPanel.setBorder(new CustomTitleBorder("Annotation -", "Configure"));
        graphPanel.setBorder(new CustomTitleBorder("Graph -", "Configure"));
    }// </editor-fold>//GEN-END:initComponents

	private void by_percentileRB_valActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_by_percentileRB_valActionPerformed
		if (sgt.is_listening) {
			switchView(true);
		}
	}//GEN-LAST:event_by_percentileRB_valActionPerformed

	private void fgColorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fgColorComboBoxActionPerformed
		if (sgt.is_listening) {
			sgt.fgColorComboBoxActionPerformed();
		}
}//GEN-LAST:event_fgColorComboBoxActionPerformed

	private void bgColorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgColorComboBoxActionPerformed
		if (sgt.is_listening) {
			sgt.bgColorComboBoxActionPerformed();
		}
	}//GEN-LAST:event_bgColorComboBoxActionPerformed

	private void nameSizeComboBoxtrackNameSizeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSizeComboBoxtrackNameSizeComboBoxActionPerformed
		if (sgt.is_listening) {
			sgt.setNameSize(nameSizeComboBox.getSelectedItem().toString());
		}
	}//GEN-LAST:event_nameSizeComboBoxtrackNameSizeComboBoxActionPerformed

	private void rangeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rangeSliderStateChanged
	}//GEN-LAST:event_rangeSliderStateChanged

	private void minTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minTextActionPerformed
		if (sgt.is_listening) {
			int min;
			int max;
			try {
				min = Integer.parseInt(minText.getText());
				max = Integer.parseInt(maxText.getText());
			} catch (Exception e) {
				return;
			}
			updateRange(min, max);
		}
	}//GEN-LAST:event_minTextActionPerformed

	private void maxTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxTextActionPerformed
		if (sgt.is_listening) {
			int min;
			int max;
			try {
				min = Integer.parseInt(minText.getText());
				max = Integer.parseInt(maxText.getText());
			} catch (Exception e) {
				return;
			}
			updateRange(min, max);
		}
	}//GEN-LAST:event_maxTextActionPerformed

	private void pluginPrefButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pluginPrefButtonActionPerformed
		TrackAdjusterPreferences pp = TrackAdjusterPreferences.getSingleton(igbService);
		pp.setTab(TrackAdjusterPreferences.TAB_DISPLAY_PLUGIN);
		javax.swing.JFrame f = pp.getFrame();
		f.setVisible(true);
	}//GEN-LAST:event_pluginPrefButtonActionPerformed

	private void by_valRB_valActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_by_valRB_valActionPerformed
		switchView(false);
	}//GEN-LAST:event_by_valRB_valActionPerformed

	private void trackNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackNameTextFieldActionPerformed
		if (sgt.is_listening) {
			sgt.setTrackName(trackNameTextField.getText());
		}
	}//GEN-LAST:event_trackNameTextFieldActionPerformed

	private void maxStackDepthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxStackDepthTextFieldActionPerformed
		if (sgt.is_listening) {
			sgt.setMaxDepth(maxStackDepthTextField.getText());
		}
	}//GEN-LAST:event_maxStackDepthTextFieldActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		if (sgt.is_listening) {
			maxStackDepthTextFieldActionPerformed(evt);
		}
	}//GEN-LAST:event_jButton2ActionPerformed

	private void AnnotationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnotationButtonActionPerformed
		if (sgt.is_listening) {
			sgt.setViewMode(DisplayType.ANNOTATION);
		}
	}//GEN-LAST:event_AnnotationButtonActionPerformed

	private void GraphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphButtonActionPerformed
		if (sgt.is_listening) {
			sgt.setViewMode(DisplayType.GRAPH);
		}
	}//GEN-LAST:event_GraphButtonActionPerformed

	private void AutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoButtonActionPerformed
		if (sgt.is_listening) {
			sgt.setViewMode(DisplayType.AUTO);
		}
	}//GEN-LAST:event_AutoButtonActionPerformed

	private void PluginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PluginButtonActionPerformed
		if (sgt.is_listening) {
			sgt.setViewMode(DisplayType.PLUGIN);
		}
	}//GEN-LAST:event_PluginButtonActionPerformed

	private void floatingCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floatingCheckBoxActionPerformed
	}//GEN-LAST:event_floatingCheckBoxActionPerformed

	private void StylePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StylePanelMouseClicked
		Rectangle bounds = new Rectangle(43, 5, 57, 13);
		if (bounds.contains(evt.getX(), evt.getY())) {
			TrackAdjusterPreferences pp = TrackAdjusterPreferences.getSingleton(igbService);
			pp.setTab(TrackAdjusterPreferences.TAB_STYLE);
			javax.swing.JFrame f = pp.getFrame();
			f.setVisible(true);
		}

	}//GEN-LAST:event_StylePanelMouseClicked

	private void AnnotationPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnnotationPanelMouseClicked
		Rectangle bounds = new Rectangle(85, 5, 55, 13);
		if (bounds.contains(evt.getX(), evt.getY())) {
			TrackAdjusterPreferences pp = TrackAdjusterPreferences.getSingleton(igbService);
			pp.setTab(TrackAdjusterPreferences.TAB_ANNOTATION);
			javax.swing.JFrame f = pp.getFrame();
			f.setVisible(true);
		}
	}//GEN-LAST:event_AnnotationPanelMouseClicked

	private void RangePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RangePanelMouseClicked
		Rectangle bounds = new Rectangle(100, 5, 53, 13);
		if (bounds.contains(evt.getX(), evt.getY())) {
			TrackAdjusterPreferences pp = TrackAdjusterPreferences.getSingleton(igbService);
			pp.setTab(TrackAdjusterPreferences.TAB_VISIBLE_RANGE);
			javax.swing.JFrame f = pp.getFrame();
			f.setVisible(true);
		}
	}//GEN-LAST:event_RangePanelMouseClicked

	private void graphPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graphPanelMouseClicked
		Rectangle bounds = new Rectangle(50, 5, 60, 13);
		if (bounds.contains(evt.getX(), evt.getY())) {
			TrackAdjusterPreferences pp = TrackAdjusterPreferences.getSingleton(igbService);
			pp.setTab(TrackAdjusterPreferences.TAB_GRAPH);
			javax.swing.JFrame f = pp.getFrame();
			f.setVisible(true);
		}
	}//GEN-LAST:event_graphPanelMouseClicked

	private void height_sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_height_sliderStateChanged
		if (sgt.glyphs.isEmpty() || !sgt.is_listening) {
			return;
		}
		sgt.setGraphHeight(height_slider.getValue());
	}//GEN-LAST:event_height_sliderStateChanged

	private void fitViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fitViewButtonActionPerformed
		int ourOptimum = 1;
		for (TierGlyph tg : sgt.selectedTiers) {
			ourOptimum = Math.max(ourOptimum, tg.getSlotsNeeded(igbService.getSeqMapView().getSeqMap().getView()));
		}
		changeMaxExpand(sgt.selectedTiers, ourOptimum);
	}//GEN-LAST:event_fitViewButtonActionPerformed

	private void collapseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collapseButtonActionPerformed
		CollapseExpandAction.getAction().actionPerformed(evt);
	}//GEN-LAST:event_collapseButtonActionPerformed

	private void selectAllBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectAllBMouseClicked
		sgt.selectAllBMouseClicked(selectAllB, evt);
	}//GEN-LAST:event_selectAllBMouseClicked

	private void StylePanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StylePanelMouseMoved
		Rectangle bounds = new Rectangle(43, 5, 57, 13);
		if (bounds.contains(evt.getX(), evt.getY())) {
			this.setCursor(openHandCursor);
		} else {
			this.setCursor(defaultCursor);
		}
	}//GEN-LAST:event_StylePanelMouseMoved

	private void AnnotationPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnnotationPanelMouseMoved
		Rectangle bounds = new Rectangle(85, 5, 55, 13);
		if (bounds.contains(evt.getX(), evt.getY())) {
			this.setCursor(openHandCursor);
		} else {
			this.setCursor(defaultCursor);
		}
	}//GEN-LAST:event_AnnotationPanelMouseMoved

	private void RangePanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RangePanelMouseMoved
		Rectangle bounds = new Rectangle(100, 5, 53, 13);
		if (bounds.contains(evt.getX(), evt.getY())) {
			this.setCursor(openHandCursor);
		} else {
			this.setCursor(defaultCursor);
		}
	}//GEN-LAST:event_RangePanelMouseMoved

	private void graphPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graphPanelMouseMoved
		Rectangle bounds = new Rectangle(50, 5, 60, 13);
		if (bounds.contains(evt.getX(), evt.getY())) {
			this.setCursor(openHandCursor);
		} else {
			this.setCursor(defaultCursor);
		}
	}//GEN-LAST:event_graphPanelMouseMoved
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AnnotationButton;
    private javax.swing.JPanel AnnotationPanel;
    private javax.swing.JRadioButton AutoButton;
    private javax.swing.ButtonGroup DisplayButtonGroup;
    private javax.swing.ButtonGroup DisplayModeButtonGroup;
    private javax.swing.JRadioButton GraphButton;
    private javax.swing.JRadioButton PluginButton;
    private javax.swing.JComboBox PluginComboBox;
    private javax.swing.JRadioButton PluginRadioButton;
    private javax.swing.JPanel RangePanel;
    private javax.swing.JPanel StylePanel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.ButtonGroup VisibleRangeButtonGroup;
    private javax.swing.JRadioButton barB;
    private com.jidesoft.combobox.ColorComboBox bgColorComboBox;
    private javax.swing.JLabel bgLabel;
    private javax.swing.JRadioButton by_percentileRB_val;
    private javax.swing.JRadioButton by_valRB_val;
    private javax.swing.JButton collapseButton;
    private javax.swing.JComboBox colorSchemeChooser;
    private javax.swing.JRadioButton dotB;
    private com.jidesoft.combobox.ColorComboBox fgColorComboBox;
    private javax.swing.JLabel fgLabel;
    private javax.swing.JButton fitViewButton;
    private javax.swing.JCheckBox floatingCheckBox;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JSlider height_slider;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox labelCB;
    private javax.swing.JRadioButton lineB;
    private javax.swing.JTextField maxStackDepthTextField;
    private javax.swing.JTextField maxText;
    private javax.swing.JLabel maxValLabel;
    private javax.swing.JTextField minText;
    private javax.swing.JLabel minValLabel;
    private javax.swing.JRadioButton mmavgB;
    private javax.swing.JComboBox nameSizeComboBox;
    private javax.swing.JButton pluginPrefButton;
    private javax.swing.JSlider rangeSlider;
    private javax.swing.JButton selectAllB;
    private javax.swing.ButtonGroup stylegroup;
    private javax.swing.JTextField trackNameTextField;
    private javax.swing.JCheckBox yaxisCB;
    // End of variables declaration//GEN-END:variables

	private void updateRange(int min, int max) {
		if (min < rangeSlider.getMinimum()) {
			rangeSlider.setMinimum(min);
		}
		if (max > rangeSlider.getMaximum()) {
			rangeSlider.setMaximum(max);
		}
	}

	@Override
	public boolean isEmbedded() {
		return true;
	}

	private void switchView(boolean b) {
		if (b) {
			org.jdesktop.layout.GroupLayout layout = (org.jdesktop.layout.GroupLayout) RangePanel.getLayout();
			layout.replace(minText, sgt.vis_bounds_setter.min_perT);
			layout.replace(maxText, sgt.vis_bounds_setter.max_perT);
			layout.replace(rangeSlider, sgt.vis_bounds_setter.PercentSlider);
			minText = sgt.vis_bounds_setter.min_perT;
			maxText = sgt.vis_bounds_setter.max_perT;
			rangeSlider = sgt.vis_bounds_setter.PercentSlider;
		} else {
			org.jdesktop.layout.GroupLayout layout = (org.jdesktop.layout.GroupLayout) RangePanel.getLayout();
			layout.replace(minText, sgt.vis_bounds_setter.min_valT);
			layout.replace(maxText, sgt.vis_bounds_setter.max_valT);
			layout.replace(rangeSlider, sgt.vis_bounds_setter.ValueSlider);
			minText = sgt.vis_bounds_setter.min_valT;
			maxText = sgt.vis_bounds_setter.max_valT;
			rangeSlider = sgt.vis_bounds_setter.ValueSlider;
		}
	}

	private void changeMaxExpand(List<TierGlyph> selectedTiers, int max) {
		for (TierGlyph tier : selectedTiers) {
			ITrackStyleExtended style = tier.getAnnotStyle();
			switch (tier.getDirection()) {
				case FORWARD:
					style.setForwardMaxDepth(max);
					break;
				case REVERSE:
					style.setReverseMaxDepth(max);
					break;
				default:
				case BOTH:
				case NONE:
				case AXIS:
					style.setMaxDepth(max);
			}
			repackStub.repack(true);
			String depth = "" + max;
			maxStackDepthTextField.setText(depth);
		}
	}
}
