package com.affymetrix.igb.view;

import com.affymetrix.genometryImpl.util.DisplayUtils;
import com.affymetrix.genometryImpl.util.PreferenceUtils;
import com.affymetrix.igb.view.WebLinksView.WebLinksTableModel;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author nick
 */
public class WebLinksViewGUI extends JPanel {

	public static WebLinksView wlv;
	public static JFrame static_frame = null;
	private static WebLinksViewGUI singleton;

	public static synchronized WebLinksViewGUI getSingleton() {
		if (singleton == null) {
			singleton = new WebLinksViewGUI();
		}
		return singleton;
	}

	public synchronized JFrame displayPanel() {
		if (static_frame == null) {
			static_frame = PreferenceUtils.createFrame("Web Links",
					getSingleton());
		}
		DisplayUtils.bringFrameToFront(static_frame);
		return static_frame;
	}

	/** Creates new form WebLinksViewGUI */
	public WebLinksViewGUI() {
		wlv = WebLinksView.getSingleton();

		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        propertiesPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = wlv.nameTextField;
        urlLabel = new javax.swing.JLabel();
        allTiersRadioButton = wlv.allTiersRadioButton;
        matchTierRadioButton = wlv.matchTierRadioButton;
        regexTextField = wlv.regexTextField;
        urlTextField = wlv.urlTextField;
        webLinkListPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        localTable = wlv.localTable;
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        importButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sysTable = wlv.sysTable;

        propertiesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Properties"));

        nameLabel.setText("Name:");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        urlLabel.setText("URL:");

        allTiersRadioButton.setText("All Tiers");
        allTiersRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allTiersRadioButtonActionPerformed(evt);
            }
        });

        matchTierRadioButton.setText("Match Tier");
        matchTierRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matchTierRadioButtonActionPerformed(evt);
            }
        });

        regexTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regexTextFieldActionPerformed(evt);
            }
        });

        urlTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlTextFieldActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout propertiesPanelLayout = new org.jdesktop.layout.GroupLayout(propertiesPanel);
        propertiesPanel.setLayout(propertiesPanelLayout);
        propertiesPanelLayout.setHorizontalGroup(
            propertiesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(propertiesPanelLayout.createSequentialGroup()
                .add(propertiesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, urlLabel)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, nameLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(propertiesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(urlTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                    .add(nameTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)))
            .add(propertiesPanelLayout.createSequentialGroup()
                .add(allTiersRadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(matchTierRadioButton)
                .add(5, 5, 5)
                .add(regexTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
        );
        propertiesPanelLayout.setVerticalGroup(
            propertiesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(propertiesPanelLayout.createSequentialGroup()
                .add(propertiesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nameLabel)
                    .add(nameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(propertiesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(urlTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(urlLabel))
                .add(5, 5, 5)
                .add(propertiesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(allTiersRadioButton)
                    .add(regexTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(matchTierRadioButton)))
        );

        webLinkListPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Local"));

        localTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                localTableFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(localTable);

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        importButton.setText("Import");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        exportButton.setText("Export");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout webLinkListPanelLayout = new org.jdesktop.layout.GroupLayout(webLinkListPanel);
        webLinkListPanel.setLayout(webLinkListPanelLayout);
        webLinkListPanelLayout.setHorizontalGroup(
            webLinkListPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(webLinkListPanelLayout.createSequentialGroup()
                .add(addButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(deleteButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 111, Short.MAX_VALUE)
                .add(importButton)
                .add(0, 0, 0)
                .add(exportButton))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );
        webLinkListPanelLayout.setVerticalGroup(
            webLinkListPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, webLinkListPanelLayout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .add(0, 0, 0)
                .add(webLinkListPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(addButton)
                    .add(deleteButton)
                    .add(exportButton)
                    .add(importButton)))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("System Default"));

        sysTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sysTableFocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(sysTable);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, webLinkListPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, propertiesPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(webLinkListPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(propertiesPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	private void allTiersRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allTiersRadioButtonActionPerformed
		regexTextField.setText("Display link for all tiers (uneditable)");
		regexTextField.setEnabled(false);
	}//GEN-LAST:event_allTiersRadioButtonActionPerformed

	private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
		wlv.localAdd();
		
	}//GEN-LAST:event_addButtonActionPerformed

	private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
		wlv.localDelete();
	}//GEN-LAST:event_deleteButtonActionPerformed

	private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
		wlv.localModel = (WebLinksTableModel)localTable.getModel();
		wlv.nameTextField();
	}//GEN-LAST:event_nameTextFieldActionPerformed

	private void urlTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlTextFieldActionPerformed
		wlv.localModel = (WebLinksTableModel)localTable.getModel();
		wlv.urlTextField();
	}//GEN-LAST:event_urlTextFieldActionPerformed

	private void regexTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regexTextFieldActionPerformed
		wlv.localModel = (WebLinksTableModel)localTable.getModel();
		wlv.regexTextField();
	}//GEN-LAST:event_regexTextFieldActionPerformed

	private void matchTierRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matchTierRadioButtonActionPerformed
		regexTextField.setEnabled(true);
		regexTextField.setText("Type your regular expression here");
		regexTextField.selectAll();
		regexTextField.requestFocusInWindow();
	}//GEN-LAST:event_matchTierRadioButtonActionPerformed

	private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
		wlv.importWebLinks();
	}//GEN-LAST:event_importButtonActionPerformed

	private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
		wlv.exportWebLinks();
	}//GEN-LAST:event_exportButtonActionPerformed

	private void localTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_localTableFocusGained
		wlv.sysModel.fireTableDataChanged();   // Deselected table
	}//GEN-LAST:event_localTableFocusGained

	private void sysTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sysTableFocusGained
		wlv.localModel.fireTableDataChanged(); // Deselected table
	}//GEN-LAST:event_sysTableFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JRadioButton allTiersRadioButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton exportButton;
    private javax.swing.JButton importButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable localTable;
    private javax.swing.JRadioButton matchTierRadioButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel propertiesPanel;
    private javax.swing.JTextField regexTextField;
    private javax.swing.JTable sysTable;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JTextField urlTextField;
    private javax.swing.JPanel webLinkListPanel;
    // End of variables declaration//GEN-END:variables
}
