/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TrackPreferences.java
 *
 * Created on June 5, 2012, 11:46:51 AM
 */
package com.affymetrix.igb.shared;

/**
 *
 * @author auser
 */
public class TrackPreferencesGUI extends javax.swing.JPanel {
	private static final long serialVersionUID = 1L;

	/** Creates new form TrackPreferencesGUI */
    public TrackPreferencesGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        stylePanel = new javax.swing.JPanel();
        labelSizeComboBox = new javax.swing.JComboBox();
        labelSizeLabel = new javax.swing.JLabel();
        colorSchemeLabel = new javax.swing.JLabel();
        colorSchemeComboBox = new javax.swing.JComboBox();
        refreshCheckBox = new javax.swing.JCheckBox();
        restoreDefaultsButton = new javax.swing.JButton();
        foregroundColorComboBox = new com.jidesoft.combobox.ColorComboBox();
        foregroundColorLabel = new javax.swing.JLabel();
        backgroundColorLabel = new javax.swing.JLabel();
        backgroundColorComboBox = new com.jidesoft.combobox.ColorComboBox();
        labelColorLabel = new javax.swing.JLabel();
        labelColorComboBox = new com.jidesoft.combobox.ColorComboBox();
        strandsForwardColorLabel1 = new javax.swing.JLabel();
        graphPanel = new javax.swing.JPanel();
        graphStyleLineRadioButton = new javax.swing.JRadioButton();
        graphStyleBarRadioButton = new javax.swing.JRadioButton();
        graphStyleStaiStepRadioButton = new javax.swing.JRadioButton();
        floatCheckBox = new javax.swing.JCheckBox();
        yAxisCheckBox = new javax.swing.JCheckBox();
        graphStyleHeatMapRadioButton = new javax.swing.JRadioButton();
        graphStylesLabel = new javax.swing.JLabel();
        graphStyleDotRadioButton = new javax.swing.JRadioButton();
        graphStyleMinMaxAvgRadioButton = new javax.swing.JRadioButton();
        graphStyleHeatMapComboBox = new javax.swing.JComboBox();
        heightLabel = new javax.swing.JLabel();
        heightSlider = new javax.swing.JSlider();
        nameLabel = new javax.swing.JLabel();
        trackNameTextField = new javax.swing.JTextField();
        viewModeComboBox = new javax.swing.JComboBox();
        viewModeLabel = new javax.swing.JLabel();
        annotationsPanel = new javax.swing.JPanel();
        collapsedCheckBox = new javax.swing.JCheckBox();
        stackDepthLabel = new javax.swing.JLabel();
        stackDepthTextField = new javax.swing.JTextField();
        labelFieldLabel = new javax.swing.JLabel();
        labelFieldComboBox = new javax.swing.JComboBox();
        strands2TracksCheckBox = new javax.swing.JCheckBox();
        strandsArrowCheckBox = new javax.swing.JCheckBox();
        strandsColorCheckBox = new javax.swing.JCheckBox();
        strandsLabel = new javax.swing.JLabel();
        strandsForwardColorLabel = new javax.swing.JLabel();
        strandsReverseColorLabel = new javax.swing.JLabel();
        strandsReverseColorComboBox = new com.jidesoft.combobox.ColorComboBox();
        strandsForewardColorComboBox = new com.jidesoft.combobox.ColorComboBox();
        selectAllComboBox = new javax.swing.JComboBox();

        org.jdesktop.layout.GroupLayout jFrame1Layout = new org.jdesktop.layout.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        stylePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Style"));

        labelSizeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12 pt", "14 pt", "32 pt" }));
        labelSizeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelSizeComboBoxActionPerformed(evt);
            }
        });

        labelSizeLabel.setText("Size:");

        colorSchemeLabel.setText("Color Scheme:");

        colorSchemeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12 pt" }));
        colorSchemeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorSchemeComboBoxActionPerformed(evt);
            }
        });

        refreshCheckBox.setText("Refresh");
        refreshCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshCheckBoxActionPerformed(evt);
            }
        });

        restoreDefaultsButton.setText("Restore Defaults");
        restoreDefaultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreDefaultsButtonActionPerformed(evt);
            }
        });

        foregroundColorComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        foregroundColorComboBox.setButtonVisible(false);
        foregroundColorComboBox.setColorValueVisible(false);
        foregroundColorComboBox.setMaximumSize(new java.awt.Dimension(150, 20));
        foregroundColorComboBox.setStretchToFit(true);

        foregroundColorLabel.setText("FG:");

        backgroundColorLabel.setText("BG:");

        backgroundColorComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        backgroundColorComboBox.setButtonVisible(false);
        backgroundColorComboBox.setColorValueVisible(false);
        backgroundColorComboBox.setMaximumSize(new java.awt.Dimension(150, 20));
        backgroundColorComboBox.setStretchToFit(true);

        labelColorLabel.setText("Label:");

        labelColorComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        labelColorComboBox.setButtonVisible(false);
        labelColorComboBox.setColorValueVisible(false);
        labelColorComboBox.setMaximumSize(new java.awt.Dimension(150, 20));
        labelColorComboBox.setStretchToFit(true);

        strandsForwardColorLabel1.setText("+");

        org.jdesktop.layout.GroupLayout stylePanelLayout = new org.jdesktop.layout.GroupLayout(stylePanel);
        stylePanel.setLayout(stylePanelLayout);
        stylePanelLayout.setHorizontalGroup(
            stylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, stylePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(stylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(stylePanelLayout.createSequentialGroup()
                        .add(stylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(stylePanelLayout.createSequentialGroup()
                                .add(foregroundColorLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(foregroundColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(backgroundColorLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(backgroundColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(colorSchemeLabel)
                            .add(colorSchemeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 148, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(refreshCheckBox)
                            .add(restoreDefaultsButton))
                        .addContainerGap())
                    .add(stylePanelLayout.createSequentialGroup()
                        .add(labelColorLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(labelSizeLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelSizeComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .add(stylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(stylePanelLayout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(strandsForwardColorLabel1)
                    .add(0, 0, Short.MAX_VALUE)))
        );
        stylePanelLayout.setVerticalGroup(
            stylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(stylePanelLayout.createSequentialGroup()
                .add(stylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(foregroundColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(foregroundColorLabel)
                    .add(backgroundColorLabel)
                    .add(backgroundColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(13, 13, 13)
                .add(stylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelSizeLabel)
                    .add(labelSizeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labelColorLabel)
                    .add(labelColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(7, 7, 7)
                .add(colorSchemeLabel)
                .add(5, 5, 5)
                .add(colorSchemeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(refreshCheckBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(restoreDefaultsButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(stylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(stylePanelLayout.createSequentialGroup()
                    .add(0, 0, Short.MAX_VALUE)
                    .add(strandsForwardColorLabel1)
                    .add(0, 0, Short.MAX_VALUE)))
        );

        graphPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Graph"));

        graphStyleLineRadioButton.setText("Line");

        graphStyleBarRadioButton.setText("Bar");

        graphStyleStaiStepRadioButton.setText("StairStep");

        floatCheckBox.setText("Float");
        floatCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floatCheckBoxActionPerformed(evt);
            }
        });

        yAxisCheckBox.setText("Y-axis");

        graphStylesLabel.setText("Graph Styles:");

        graphStyleDotRadioButton.setText("Dot");

        graphStyleMinMaxAvgRadioButton.setText("min/max/mean");

        graphStyleHeatMapComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Heat Map" }));
        graphStyleHeatMapComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphStyleHeatMapComboBoxActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout graphPanelLayout = new org.jdesktop.layout.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(graphPanelLayout.createSequentialGroup()
                .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(graphPanelLayout.createSequentialGroup()
                        .add(graphStyleHeatMapRadioButton)
                        .add(5, 5, 5)
                        .add(graphStyleHeatMapComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(graphStyleStaiStepRadioButton)
                    .add(graphPanelLayout.createSequentialGroup()
                        .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(graphPanelLayout.createSequentialGroup()
                                .add(graphStyleLineRadioButton)
                                .add(7, 7, 7))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, floatCheckBox))
                        .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(graphPanelLayout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(yAxisCheckBox))
                            .add(graphPanelLayout.createSequentialGroup()
                                .add(19, 19, 19)
                                .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(graphStyleDotRadioButton)
                                    .add(graphStyleBarRadioButton)))))
                    .add(graphPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(graphStylesLabel))
                    .add(graphStyleMinMaxAvgRadioButton))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, graphPanelLayout.createSequentialGroup()
                .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(floatCheckBox)
                    .add(yAxisCheckBox))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(graphStylesLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(graphStyleLineRadioButton)
                    .add(graphStyleBarRadioButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(graphStyleStaiStepRadioButton)
                    .add(graphStyleDotRadioButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(graphStyleMinMaxAvgRadioButton)
                .add(4, 4, 4)
                .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(graphStyleHeatMapRadioButton)
                    .add(graphStyleHeatMapComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        heightLabel.setText("Height:");

        nameLabel.setText("Name:");

        viewModeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mode" }));

        viewModeLabel.setText("View Mode:");

        annotationsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Annotations"));

        collapsedCheckBox.setText("Collapse");

        stackDepthLabel.setText("Stack Depth:");

        stackDepthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stackDepthTextFieldActionPerformed(evt);
            }
        });

        labelFieldLabel.setText("Label Field:");

        labelFieldComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12 pt" }));
        labelFieldComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelFieldComboBoxActionPerformed(evt);
            }
        });

        strands2TracksCheckBox.setText("2 track");
        strands2TracksCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strands2TracksCheckBoxActionPerformed(evt);
            }
        });

        strandsArrowCheckBox.setText("Arrow");

        strandsColorCheckBox.setText("Color:");

        strandsLabel.setText("+/- Strands:");

        strandsForwardColorLabel.setText("+");

        strandsReverseColorLabel.setText("-");

        strandsReverseColorComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        strandsReverseColorComboBox.setButtonVisible(false);
        strandsReverseColorComboBox.setColorValueVisible(false);
        strandsReverseColorComboBox.setMaximumSize(new java.awt.Dimension(150, 20));
        strandsReverseColorComboBox.setStretchToFit(true);

        strandsForewardColorComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        strandsForewardColorComboBox.setButtonVisible(false);
        strandsForewardColorComboBox.setColorValueVisible(false);
        strandsForewardColorComboBox.setMaximumSize(new java.awt.Dimension(150, 20));
        strandsForewardColorComboBox.setStretchToFit(true);

        org.jdesktop.layout.GroupLayout annotationsPanelLayout = new org.jdesktop.layout.GroupLayout(annotationsPanel);
        annotationsPanel.setLayout(annotationsPanelLayout);
        annotationsPanelLayout.setHorizontalGroup(
            annotationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(annotationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(annotationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(annotationsPanelLayout.createSequentialGroup()
                        .add(stackDepthLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(stackDepthTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(annotationsPanelLayout.createSequentialGroup()
                        .add(labelFieldLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(labelFieldComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(strandsLabel)
                    .add(annotationsPanelLayout.createSequentialGroup()
                        .add(strandsColorCheckBox)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(strandsForwardColorLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(strandsForewardColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(strandsReverseColorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(strandsReverseColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(annotationsPanelLayout.createSequentialGroup()
                        .add(strands2TracksCheckBox)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(strandsArrowCheckBox))
                    .add(collapsedCheckBox))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        annotationsPanelLayout.setVerticalGroup(
            annotationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(annotationsPanelLayout.createSequentialGroup()
                .add(annotationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(stackDepthLabel)
                    .add(stackDepthTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(annotationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelFieldLabel)
                    .add(labelFieldComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(4, 4, 4)
                .add(collapsedCheckBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(strandsLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(annotationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(strands2TracksCheckBox)
                    .add(strandsArrowCheckBox))
                .add(2, 2, 2)
                .add(annotationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(strandsColorCheckBox)
                    .add(strandsForwardColorLabel)
                    .add(strandsReverseColorLabel)
                    .add(strandsReverseColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(strandsForewardColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        selectAllComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(heightLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(heightSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 199, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(viewModeLabel))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(nameLabel)
                                .add(18, 18, 18)
                                .add(trackNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 292, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(layout.createSequentialGroup()
                        .add(11, 11, 11)
                        .add(stylePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(annotationsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(selectAllComboBox, 0, 206, Short.MAX_VALUE)
                            .add(viewModeComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .add(graphPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(nameLabel)
                    .add(trackNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(selectAllComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(7, 7, 7)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(heightSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(heightLabel)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(viewModeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(viewModeLabel)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(stylePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(annotationsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(graphPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelSizeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelSizeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSizeComboBoxActionPerformed

    private void floatCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floatCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floatCheckBoxActionPerformed

    private void restoreDefaultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreDefaultsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restoreDefaultsButtonActionPerformed

    private void strands2TracksCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strands2TracksCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strands2TracksCheckBoxActionPerformed

    private void stackDepthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stackDepthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stackDepthTextFieldActionPerformed

    private void colorSchemeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorSchemeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorSchemeComboBoxActionPerformed

    private void refreshCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshCheckBoxActionPerformed

    private void labelFieldComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelFieldComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelFieldComboBoxActionPerformed

    private void graphStyleHeatMapComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphStyleHeatMapComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_graphStyleHeatMapComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel annotationsPanel;
    private com.jidesoft.combobox.ColorComboBox backgroundColorComboBox;
    private javax.swing.JLabel backgroundColorLabel;
    private javax.swing.JCheckBox collapsedCheckBox;
    private javax.swing.JComboBox colorSchemeComboBox;
    private javax.swing.JLabel colorSchemeLabel;
    private javax.swing.JCheckBox floatCheckBox;
    private com.jidesoft.combobox.ColorComboBox foregroundColorComboBox;
    private javax.swing.JLabel foregroundColorLabel;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JRadioButton graphStyleBarRadioButton;
    private javax.swing.JRadioButton graphStyleDotRadioButton;
    private javax.swing.JComboBox graphStyleHeatMapComboBox;
    private javax.swing.JRadioButton graphStyleHeatMapRadioButton;
    private javax.swing.JRadioButton graphStyleLineRadioButton;
    private javax.swing.JRadioButton graphStyleMinMaxAvgRadioButton;
    private javax.swing.JRadioButton graphStyleStaiStepRadioButton;
    private javax.swing.JLabel graphStylesLabel;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JSlider heightSlider;
    private javax.swing.JFrame jFrame1;
    private com.jidesoft.combobox.ColorComboBox labelColorComboBox;
    private javax.swing.JLabel labelColorLabel;
    private javax.swing.JComboBox labelFieldComboBox;
    private javax.swing.JLabel labelFieldLabel;
    private javax.swing.JComboBox labelSizeComboBox;
    private javax.swing.JLabel labelSizeLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JCheckBox refreshCheckBox;
    private javax.swing.JButton restoreDefaultsButton;
    private javax.swing.JComboBox selectAllComboBox;
    private javax.swing.JLabel stackDepthLabel;
    private javax.swing.JTextField stackDepthTextField;
    private javax.swing.JCheckBox strands2TracksCheckBox;
    private javax.swing.JCheckBox strandsArrowCheckBox;
    private javax.swing.JCheckBox strandsColorCheckBox;
    private com.jidesoft.combobox.ColorComboBox strandsForewardColorComboBox;
    private javax.swing.JLabel strandsForwardColorLabel;
    private javax.swing.JLabel strandsForwardColorLabel1;
    private javax.swing.JLabel strandsLabel;
    private com.jidesoft.combobox.ColorComboBox strandsReverseColorComboBox;
    private javax.swing.JLabel strandsReverseColorLabel;
    private javax.swing.JPanel stylePanel;
    private javax.swing.JTextField trackNameTextField;
    private javax.swing.JComboBox viewModeComboBox;
    private javax.swing.JLabel viewModeLabel;
    private javax.swing.JCheckBox yAxisCheckBox;
    // End of variables declaration//GEN-END:variables


 // getters generated by Eclipse, NetBeans balked: "Read-only block of text cannot be refactored."
	public javax.swing.JPanel getAnnotationsPanel() {
		return annotationsPanel;
	}

	public com.jidesoft.combobox.ColorComboBox getBackgroundColorComboBox() {
		return backgroundColorComboBox;
	}

	public javax.swing.JLabel getBackgroundColorLabel() {
		return backgroundColorLabel;
	}

	public javax.swing.JCheckBox getCollapsedCheckBox() {
		return collapsedCheckBox;
	}

	public javax.swing.JComboBox getColorSchemeComboBox() {
		return colorSchemeComboBox;
	}

	public javax.swing.JLabel getColorSchemeLabel() {
		return colorSchemeLabel;
	}

	public javax.swing.JCheckBox getFloatCheckBox() {
		return floatCheckBox;
	}

	public com.jidesoft.combobox.ColorComboBox getForegroundColorComboBox() {
		return foregroundColorComboBox;
	}

	public javax.swing.JLabel getForegroundColorLabel() {
		return foregroundColorLabel;
	}

	public javax.swing.JPanel getGraphPanel() {
		return graphPanel;
	}

	public javax.swing.JRadioButton getGraphStyleBarRadioButton() {
		return graphStyleBarRadioButton;
	}

	public javax.swing.JRadioButton getGraphStyleDotRadioButton() {
		return graphStyleDotRadioButton;
	}

	public javax.swing.JComboBox getGraphStyleHeatMapComboBox() {
		return graphStyleHeatMapComboBox;
	}

	public javax.swing.JRadioButton getGraphStyleHeatMapRadioButton() {
		return graphStyleHeatMapRadioButton;
	}

	public javax.swing.JRadioButton getGraphStyleLineRadioButton() {
		return graphStyleLineRadioButton;
	}

	public javax.swing.JRadioButton getGraphStyleMinMaxAvgRadioButton() {
		return graphStyleMinMaxAvgRadioButton;
	}

	public javax.swing.JRadioButton getGraphStyleStaiStepRadioButton() {
		return graphStyleStaiStepRadioButton;
	}

	public javax.swing.JLabel getGraphStylesLabel() {
		return graphStylesLabel;
	}

	public javax.swing.JLabel getHeightLabel() {
		return heightLabel;
	}

	public javax.swing.JSlider getHeightSlider() {
		return heightSlider;
	}

	public javax.swing.JFrame getjFrame1() {
		return jFrame1;
	}

	public com.jidesoft.combobox.ColorComboBox getLabelColorComboBox() {
		return labelColorComboBox;
	}

	public javax.swing.JLabel getLabelColorLabel() {
		return labelColorLabel;
	}

	public javax.swing.JComboBox getLabelFieldComboBox() {
		return labelFieldComboBox;
	}

	public javax.swing.JLabel getLabelFieldLabel() {
		return labelFieldLabel;
	}

	public javax.swing.JComboBox getLabelSizeComboBox() {
		return labelSizeComboBox;
	}

	public javax.swing.JLabel getLabelSizeLabel() {
		return labelSizeLabel;
	}

	public javax.swing.JLabel getNameLabel() {
		return nameLabel;
	}

	public javax.swing.JCheckBox getRefreshCheckBox() {
		return refreshCheckBox;
	}

	public javax.swing.JButton getRestoreDefaultsButton() {
		return restoreDefaultsButton;
	}

	public javax.swing.JComboBox getSelectAllComboBox() {
		return selectAllComboBox;
	}

	public javax.swing.JLabel getStackDepthLabel() {
		return stackDepthLabel;
	}

	public javax.swing.JTextField getStackDepthTextField() {
		return stackDepthTextField;
	}

	public javax.swing.JCheckBox getStrands2TracksCheckBox() {
		return strands2TracksCheckBox;
	}

	public javax.swing.JCheckBox getStrandsArrowCheckBox() {
		return strandsArrowCheckBox;
	}

	public javax.swing.JCheckBox getStrandsColorCheckBox() {
		return strandsColorCheckBox;
	}

	public com.jidesoft.combobox.ColorComboBox getStrandsForewardColorComboBox() {
		return strandsForewardColorComboBox;
	}

	public javax.swing.JLabel getStrandsForwardColorLabel() {
		return strandsForwardColorLabel;
	}

	public javax.swing.JLabel getStrandsLabel() {
		return strandsLabel;
	}

	public com.jidesoft.combobox.ColorComboBox getStrandsReverseColorComboBox() {
		return strandsReverseColorComboBox;
	}

	public javax.swing.JLabel getStrandsReverseColorLabel() {
		return strandsReverseColorLabel;
	}

	public javax.swing.JPanel getStylePanel() {
		return stylePanel;
	}

	public javax.swing.JTextField getTrackNameTextField() {
		return trackNameTextField;
	}

	public javax.swing.JComboBox getViewModeComboBox() {
		return viewModeComboBox;
	}

	public javax.swing.JLabel getViewModeLabel() {
		return viewModeLabel;
	}

	public javax.swing.JCheckBox getyAxisCheckBox() {
		return yAxisCheckBox;
	}
}
