package apollo.analysis;

import apollo.action.BlastSearchAction;
import com.affymetrix.igb.shared.IPrefEditorComponent;

/**
 *
 * @author hiralv
 */
public class RemoteBlastOptions extends IPrefEditorComponent implements BlastOptionsI {

	/**
	 * Creates new form RemoteBlastOptions
	 */
	public RemoteBlastOptions(RemoteBlastNCBI.BlastType type) {
		setName("Blast");
		setToolTipText("Edit blast options");
		initComponents();
		setBlastType(type);
	}
	
	private void setBlastType(RemoteBlastNCBI.BlastType type) {
		switch(type){
			case blastx:
				blastxRadioButton.setSelected(true);
				break;
			case tblastx:
				tblastxRadioButton.setSelected(true);
				break;
			default:
				blastnRadioButton.setSelected(true);
				break;
		}
	}
	
	public RemoteBlastNCBI.BlastType getBlastType(){
		if(blastxRadioButton.isSelected()){
			return RemoteBlastNCBI.BlastType.blastx;
		} else if (tblastxRadioButton.isSelected()) {
			return RemoteBlastNCBI.BlastType.tblastx;
		}
		return RemoteBlastNCBI.BlastType.blastn;
	}
	
	@Override
	public void refresh(){
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blastTypeGroup = new javax.swing.ButtonGroup();
        blastTypePanel = new javax.swing.JPanel();
        blastnRadioButton = new javax.swing.JRadioButton();
        blastxRadioButton = new javax.swing.JRadioButton();
        tblastxRadioButton = new javax.swing.JRadioButton();

        blastTypePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Blast Type"));

        blastTypeGroup.add(blastnRadioButton);
        blastnRadioButton.setText("blastn");

        blastTypeGroup.add(blastxRadioButton);
        blastxRadioButton.setText("blastx");

        blastTypeGroup.add(tblastxRadioButton);
        tblastxRadioButton.setText("tblastx");

        org.jdesktop.layout.GroupLayout blastTypePanelLayout = new org.jdesktop.layout.GroupLayout(blastTypePanel);
        blastTypePanel.setLayout(blastTypePanelLayout);
        blastTypePanelLayout.setHorizontalGroup(
            blastTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(blastTypePanelLayout.createSequentialGroup()
                .add(blastTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(blastnRadioButton)
                    .add(blastxRadioButton)
                    .add(tblastxRadioButton))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        blastTypePanelLayout.setVerticalGroup(
            blastTypePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(blastTypePanelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(blastnRadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(blastxRadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tblastxRadioButton))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(blastTypePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(blastTypePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup blastTypeGroup;
    private javax.swing.JPanel blastTypePanel;
    private javax.swing.JRadioButton blastnRadioButton;
    private javax.swing.JRadioButton blastxRadioButton;
    private javax.swing.JRadioButton tblastxRadioButton;
    // End of variables declaration//GEN-END:variables
}
