package apollo.analysis;

import apollo.datamodel.Sequence;
import apollo.datamodel.StrandedFeatureSet;
import apollo.datamodel.StrandedFeatureSetI;

public class RemoteBlastNCBITest {

	public static void main(String[] args) throws Exception {
		testRunAnalysis();
	}
	
	public static void testRunAnalysis() throws Exception {
		String id = "test";
		String residues = "TTCAGAGTTAAGGAACTGTATTAATCGTGTAATTTCTGCTACGAATCCGCCCATTTGTATTTAGTGTGCT"
				+ "TCATGTACTATCATTCTCCTAAATTGGTTTTTTGAGTGGTTATTAATCTGCTTTGCAGTCAGGAGGAATC"
				+ "ATCTAAGTCAGTATGGACCAGAAGAAGAGGAAGTTGGAAGATCCACCAGCCACGAATGCGAAAGAAGACA"
				+ "ACACTGCTGTAGTTGGGGGACCAACAGTGTCTGTTCCTTCTTTCGTGATCACTAAGGAGGATGTCAAGAA"
				+ "GCTTTTGGAGTCATTTACGAAGGATCGATTGATGGATTTATTGGAAAATGCTGCTCTTGTTCATACAGGT"
				+ "TATTCCTCGTCGAGTTATCTATCGTCCTAAAGCTCATTTTGGATGTGGTTTTTCAACGCGAGAGATACAG"
				+ "TGATGGGTTTATATATTTTCATGTACTGTTCAACTTATTCACATGTTCTCGATGGGTGTCGCTGTTTGAC"
				+ "TTTTGCAGATGTTCTTCAGGAAATTCGCAAGGTGGCTGACAAAGTTCCTGGTCATCGGAAGATTTTTGTA"
				+ "AGGGGCCTTGGTTGGGACTCAACGACAGAAACCTTGAAGACAGTATTCTCACAATTTGGAGAAGTGGAGG"
				+ "AGGGGGCGGTTGTTATGGACAAGGGTACTGGAAAGAGTAGAGGCTTTGGATTTGTGACATTCATACACAT"
				+ "GGACGGTGCTCAACGATCACTGAAGGAACCTAGCAAGCGGATTGATGGACGGATGACAGATTGTCAGTTG"
				+ "GCATCAACTGGGGCGTTGCAAATAAATCCTAATCAAGAAGTTTCAACGAGAAAAATTTACGTGGGCAACA"
				+ "TATCCCTTGATCTTTCTGCGGACAGGCTGCTGGCTTTTTTCGCAGGATATGGAGAAATTGGAGAGGGTCC"
				+ "CTTAGGATTCGACAAATTCACTGGACGCTCACGAGGTTTCGCTTTGTTTATTTACAAGACAGTTGAAGCT"
				+ "ACAAAGAGGGCATTGTTGGAGCCAATCAAGACTTTAGATGGTATTCAAATGTACTGTAAGCTTGCCTCTG"
				+ "AGAATCAGAAACAGGGGCAGGGGAGGCAAGGCCCTCCCGGTAAAAGCGACAATGATTTAATACTAGGCAG"
				+ "GCAGCAGGTAATCTACATCAATCATCTTGTCCATCTGAAAATGCGTTTATTCTTATGGTCGGGGACCAGT"
				+ "TTGTATTTTAAAGCTGATGTGGTGTTCATTTGATCACATGTTTTTACGAAGTGGTACTGAGAGTAGTTGT"
				+ "TGTGAGAACCTTCTGCTGGCTTTTCTTGTGTGCAGATATCAACTCCTCCGTCCCTCTCAAACGAACAAAA"
				+ "TATGTCGTACGGATCCATGAATACTGGTTCATTAACTACTGGAATTCCGCTCAACCAGGGCGTGAATCAA"
				+ "GGAATGAGTCAAGGAAGTCACATGGGTCTCAATAATCATAATCAAGGTCTTAGCAACCTGAAGAGCACAT"
				+ "TGAACTCGCCCCTCAACTATACATTGAATTCATCATTATCTCCTCTAGGACAGTTAACGAATTCATCGTT"
				+ "AAATGGTTCTTTTAACTCCGGTCACCCACAAACATCCCTTGGAATGGGATCTTACAGTTCACAATTGGCT"
				+ "GTGTCCCAATATGGAGGTCAACCAACTGGCCTTGGTGGGCAACCTACATATTCTTCGATGAATGGGGTTC"
				+ "TTTATTGCTCGGCAGCCAACTCAGCAGCCTCGCAGCAGGTATTTAAAACGAATTTTATATTGCGCATGAC"
				+ "GATTTAGTGTAGGTCCTGTAATTTGCATGCTTAACTGTCTATTTTAATTAATTACATTACATCTAATGAG"
				+ "TGAGGCCGTTCGTATTATTCGGGATAACTGTGTTGATCTTGGCGGACCTGCAGTTTGTACCGAAGTACTT"
				+ "GACGTTGCATTCGCCTAATACTATGTCCAACACATGTATATTTAAAATCTGACTTCTCTCATCTACTGTA"
				+ "TATTTCTCAGCAAGCAGCGCTGCAGGTAGCTGGTGGTCATTACGGATATGGGTCATATCAAAGTCCTCAA"
				+ "CTTCCAACATCTTCTGCTCCTCGCGCCCCTCCCGTAGGAAATATGTACATGCCTTCCAACCATAACCTAA"
				+ "AAGGTAAGCATTGGTGTCTTCACTTTCTTGCTCTTTAAGGTGCGCTATTCTTTTACTGACCAATTGTGAG"
				+ "ACCTCCTAATTAAATATGCTCGAATGATTGTCCTCTTTTCGTTCAAAGTTGCGAGTTTGGTTCACGTCTG"
				+ "AGAGAGGCATCGGAGTTTTGAATGAATATTAAATCTTGGATGTTTTATTTTGGATGTTGAATACAAATTC"
				+ "AGCAATAACAATTTTTTTGTCTGTGATGTTTCATGTCTGGATTATCTACATGTCTGTGATCACTGTTCAG"
				+ "TGTATACAAGAGTTTCAGTTGTTTTCAATTAGGATGATTATGTTTGTGCTACATTGGGCAACAGAGGTTA"
				+ "TTTGTGAGAAGGGAGATTTAAGTACTAAACATTGTGCTTACTGTAAATGTTCTGTTGCGGATTTTGTTCT"
				+ "TTTGACTTTTTCTTTTTTTCTTTTTTTCTTTTCTCCAGTTCTTTGCAAATTGTGATAGTTTAACCTTTTT"
				+ "ATCTTAATAATGTTGCAAGCTTGTTGGTCTAGTTTCTTTGAGGAATTCAAGTTTCGAACGGGATATTACC"
				+ "ACAGTTTGATAGCAAATACAAAAAACAAGAGTTGAAATTAGTGGTGAAAAAGTTTGGTCATTTCATAACC"
				+ "GATGCCCATAATTTGAATCTCTGTGACTCTGAAAATCTCTAATATTTATCGTTTTTATCCATCAACTCTA"
				+ "GCGTACGCCATGCACTACTTATTGTTCTAGTAATTGACGGATCTCTGTTGACAATGTTGGTGGACATGGG"
				+ "ATTACCATGAGATAAGTTCCAGGCCCGATCGACCAGGTTTCACAAAGAAGCTTTAAAGATTATTTTTTCT"
				+ "TATCAAATTTAATGTATAAAGATCCAAAGTGGTTTATTGCCATGTTTTCAGTCAAGTAATTTCATGACTG"
				+ "AAAAGTTATGGAGACTAATTATTCCTTTTAATTGTA";
		
		StrandedFeatureSetI sf = new StrandedFeatureSet();
		Sequence seq = new Sequence(id, residues);
		
		RemoteBlastNCBI blast = new RemoteBlastNCBI(RemoteBlastNCBI.BlastType.blastn, new RemoteBlastNCBI.BlastOptions());
		blast.runAnalysis(sf, seq, 1, 1);
		
		System.out.println();
	}
}
