package com.affymetrix.igb.view;

import com.affymetrix.common.CommonUtils;
import com.affymetrix.genometryImpl.util.DisplayUtils;
import com.affymetrix.genometryImpl.util.PreferenceUtils;
import com.affymetrix.igb.IGB;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 * A Web links View UI class for IGB. It is generated by Netbeans GUI Builder.
 * All the function codes are implemented in WebLinksView class.
 *
 * @author nick
 */
public class WebLinksViewGUI extends JPanel {
	private static final long serialVersionUID = 1L;
	public static WebLinksView wlv;
	public static JFrame static_frame = null;
	private static WebLinksViewGUI singleton;

	public static synchronized WebLinksViewGUI getSingleton() {
		if (singleton == null) {
			singleton = new WebLinksViewGUI();
		}
		return singleton;
	}

	public synchronized JFrame displayPanel() {
		if (static_frame == null) {
			static_frame = PreferenceUtils.createFrame("Web Links Tool",
					getSingleton());
			static_frame.setLocationRelativeTo(IGB.getSingleton().getFrame());
		}
		DisplayUtils.bringFrameToFront(static_frame);
		return static_frame;
	}

	/**
	 * Creates new form WebLinksViewGUI
	 */
	public WebLinksViewGUI() {
		wlv = WebLinksView.getSingleton();

		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        localPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        localTable = wlv.localTable;
        createButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        importButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();
        builderPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = wlv.nameTextField;
        urlLabel = new javax.swing.JLabel();
        nameRadioButton = wlv.nameRadioButton;
        idRadioButton = wlv.idRadioButton;
        regexTextField = wlv.regexTextField;
        urlTextField = wlv.urlTextField;
        matchTip = new javax.swing.JLabel();
        regexLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        regularExpressionTip = new javax.swing.JLabel();
        defaultPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        defaultTable = wlv.serverTable;

        localPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Custom Web Links - Click To Edit"));

        localTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                localTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(localTable);

        createButton.setText("Create New");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        importButton.setText("Import");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        exportButton.setText("Export");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        builderPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Web Link Builder"));

        nameLabel.setText("Name:");

        nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextFieldKeyReleased(evt);
            }
        });

        urlLabel.setText("URL:");

        nameRadioButton.setText("Track Name");
        nameRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameRadioButtonActionPerformed(evt);
            }
        });

        idRadioButton.setText("Annotation ID");
        idRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idRadioButtonActionPerformed(evt);
            }
        });

        regexTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                regexTextFieldKeyReleased(evt);
            }
        });

        urlTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                urlTextFieldKeyReleased(evt);
            }
        });

        matchTip.setToolTipText("Choose for Regular Expression Matches");
        matchTip.setIcon(CommonUtils.getInstance().getIcon("16x16/actions/info.png"));
        matchTip.setText(" ");
        matchTip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                matchTipMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                matchTipMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                matchTipMouseEntered(evt);
            }
        });

        regexLabel.setText("Regular Expression:");

        jLabel1.setText("Regular Expression Matches:");

        regularExpressionTip.setToolTipText("Click to the instruction page.");
        regularExpressionTip.setIcon(CommonUtils.getInstance().getIcon("16x16/actions/info.png"));
        regularExpressionTip.setText(" ");
        regularExpressionTip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                regularExpressionTipMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regularExpressionTipMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regularExpressionTipMouseEntered(evt);
            }
        });

        org.jdesktop.layout.GroupLayout builderPanelLayout = new org.jdesktop.layout.GroupLayout(builderPanel);
        builderPanel.setLayout(builderPanelLayout);
        builderPanelLayout.setHorizontalGroup(
            builderPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(builderPanelLayout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nameRadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(idRadioButton)
                .add(5, 5, 5)
                .add(matchTip, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
            .add(builderPanelLayout.createSequentialGroup()
                .add(builderPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(nameLabel)
                    .add(urlLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(builderPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(urlTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                    .add(builderPanelLayout.createSequentialGroup()
                        .add(nameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 156, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(regexLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(regexTextField)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(regularExpressionTip, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(6, 6, 6))))
        );
        builderPanelLayout.setVerticalGroup(
            builderPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(builderPanelLayout.createSequentialGroup()
                .add(builderPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(regularExpressionTip)
                    .add(regexTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(regexLabel)
                    .add(nameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nameLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(builderPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(urlLabel)
                    .add(urlTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, 0)
                .add(builderPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(jLabel1)
                    .add(nameRadioButton)
                    .add(idRadioButton)
                    .add(matchTip)))
        );

        org.jdesktop.layout.GroupLayout localPanelLayout = new org.jdesktop.layout.GroupLayout(localPanel);
        localPanel.setLayout(localPanelLayout);
        localPanelLayout.setHorizontalGroup(
            localPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, localPanelLayout.createSequentialGroup()
                .add(createButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(deleteButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 232, Short.MAX_VALUE)
                .add(importButton)
                .add(0, 0, 0)
                .add(exportButton))
            .add(builderPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        localPanelLayout.setVerticalGroup(
            localPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(localPanelLayout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .add(0, 0, 0)
                .add(localPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(exportButton)
                    .add(importButton)
                    .add(createButton)
                    .add(deleteButton))
                .add(builderPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        defaultPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Server Provided Web Link"));

        defaultTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                defaultTableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(defaultTable);

        org.jdesktop.layout.GroupLayout defaultPanelLayout = new org.jdesktop.layout.GroupLayout(defaultPanel);
        defaultPanel.setLayout(defaultPanelLayout);
        defaultPanelLayout.setHorizontalGroup(
            defaultPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );
        defaultPanelLayout.setVerticalGroup(
            defaultPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(defaultPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, localPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(defaultPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(localPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void nameRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameRadioButtonActionPerformed
		wlv.nameRadioButton();
	}//GEN-LAST:event_nameRadioButtonActionPerformed

	private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
		wlv.add();
	}//GEN-LAST:event_createButtonActionPerformed

	private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
		wlv.delete();
	}//GEN-LAST:event_deleteButtonActionPerformed

	private void idRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idRadioButtonActionPerformed
		wlv.idRadioButton();
	}//GEN-LAST:event_idRadioButtonActionPerformed

	private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
		wlv.importWebLinks();
	}//GEN-LAST:event_importButtonActionPerformed

	private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
		wlv.exportWebLinks();
	}//GEN-LAST:event_exportButtonActionPerformed

	private void localTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_localTableMousePressed
		if (defaultTable.getSelectedRow() != -1
				&& localTable.getSelectedRow() != -1) {
			defaultTable.removeRowSelectionInterval(0, defaultTable.getRowCount() - 1);
		}
	}//GEN-LAST:event_localTableMousePressed

	private void defaultTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaultTableMousePressed
		if (defaultTable.getSelectedRow() != -1
				&& localTable.getSelectedRow() != -1) {
			localTable.removeRowSelectionInterval(0, localTable.getRowCount() - 1);
		}
	}//GEN-LAST:event_defaultTableMousePressed

	private void nameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextFieldKeyReleased
		wlv.nameTextFieldKeyReleased();
	}//GEN-LAST:event_nameTextFieldKeyReleased

	private void regexTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_regexTextFieldKeyReleased
		wlv.regexTextFieldKeyReleased();
	}//GEN-LAST:event_regexTextFieldKeyReleased

	private void urlTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_urlTextFieldKeyReleased
		wlv.urlTextField();
	}//GEN-LAST:event_urlTextFieldKeyReleased

	private void regularExpressionTipMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regularExpressionTipMouseReleased
		wlv.regexTipMouseReleased();
	}//GEN-LAST:event_regularExpressionTipMouseReleased

	private void regularExpressionTipMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regularExpressionTipMouseEntered
		setCursor(WebLinksView.handCursor);
	}//GEN-LAST:event_regularExpressionTipMouseEntered

	private void regularExpressionTipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regularExpressionTipMouseExited
		setCursor(WebLinksView.defaultCursor);
	}//GEN-LAST:event_regularExpressionTipMouseExited

	private void matchTipMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matchTipMouseEntered
		setCursor(WebLinksView.handCursor);
	}//GEN-LAST:event_matchTipMouseEntered

	private void matchTipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matchTipMouseExited
		setCursor(WebLinksView.defaultCursor);
	}//GEN-LAST:event_matchTipMouseExited

	private void matchTipMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matchTipMouseReleased
		wlv.regexTipMouseReleased();
	}//GEN-LAST:event_matchTipMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel builderPanel;
    private javax.swing.JButton createButton;
    private javax.swing.JPanel defaultPanel;
    private javax.swing.JTable defaultTable;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton exportButton;
    private javax.swing.JRadioButton idRadioButton;
    private javax.swing.JButton importButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel localPanel;
    private javax.swing.JTable localTable;
    private javax.swing.JLabel matchTip;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JRadioButton nameRadioButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel regexLabel;
    private javax.swing.JTextField regexTextField;
    private javax.swing.JLabel regularExpressionTip;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JTextField urlTextField;
    // End of variables declaration//GEN-END:variables
}
