package com.affymetrix.igb.trackOperations;

import com.affymetrix.igb.osgi.service.IGBService;
import com.affymetrix.igb.osgi.service.IGBTabPanel;
import java.util.ResourceBundle;

public class TrackOperationsTabGUI extends IGBTabPanel {

	private static final long serialVersionUID = 1L;
	public static final ResourceBundle BUNDLE = ResourceBundle.getBundle("trackOperations");
	private static final int TAB_POSITION = 4;
	public TrackOperationsTab trackOpTab;
	private static TrackOperationsTabGUI singleton;

	public TrackOperationsTabGUI(IGBService _igbService) {
		super(_igbService, BUNDLE.getString("trackOperationsTab"), BUNDLE.getString("trackOperationsTab"), false, TAB_POSITION);

		TrackOperationsTab.init(igbService);
		trackOpTab = TrackOperationsTab.getSingleton();
		initComponents();
	}

	public static void init(IGBService igbService) {
		singleton = new TrackOperationsTabGUI(igbService);
	}

	public static synchronized TrackOperationsTabGUI getSingleton() {
		return singleton;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        operationLabel = trackOpTab.operationLabel;
        operationCB = trackOpTab.operationCB;
        operationGoB = trackOpTab.operationGoB;
        combineB = trackOpTab.combineB;
        splitB = trackOpTab.splitB;
        operationParamLabel = trackOpTab.operationParamLabel;
        operationParam = trackOpTab.operationParam;
        threshB = trackOpTab.threshB;

        jLabel2.setText("jLabel2");

        operationLabel.setText("Operation");

        operationGoB.setText("Go");

        combineB.setText("Join");

        splitB.setText("Split");

        operationParamLabel.setText(" ");

        operationParam.setEditable(false);

        threshB.setText("Threshhold");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(32, 32, 32)
                        .add(combineB)
                        .add(26, 26, 26)
                        .add(splitB)
                        .add(31, 31, 31)
                        .add(threshB))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(operationLabel)
                            .add(operationParamLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 83, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(operationParam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(operationCB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(operationGoB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(572, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(8, 8, 8)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(operationLabel)
                    .add(operationCB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(operationGoB))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(operationParamLabel)
                    .add(operationParam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(22, 22, 22)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(combineB)
                    .add(splitB)
                    .add(threshB))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combineB;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox operationCB;
    private javax.swing.JButton operationGoB;
    private javax.swing.JLabel operationLabel;
    private javax.swing.JTextField operationParam;
    private javax.swing.JLabel operationParamLabel;
    private javax.swing.JButton splitB;
    private javax.swing.JButton threshB;
    // End of variables declaration//GEN-END:variables

	@Override
	public boolean isEmbedded() {
		return true;
	}
}
