/*
 * TrackPreferences.java
 *
 * Created on June 5, 2012, 11:46:51 AM
 */
package com.affymetrix.igb.shared;

import com.affymetrix.genoviz.color.ColorScheme;
import com.affymetrix.genoviz.color.ColorSchemeComboBox;
import com.affymetrix.genoviz.swing.NumericFilter;
import static com.affymetrix.igb.shared.Selections.allStyles;
import static com.affymetrix.igb.shared.Selections.annotStyles;
import static com.affymetrix.igb.shared.Selections.graphStates;
import com.affymetrix.igb.swing.JRPTextField;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JRadioButton;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author auser
 */
public abstract class TrackPreferencesGUI extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    protected boolean is_listening = true; // used to turn on and off listening to GUI events	
    private static final Object[] SUPPORTED_SIZE = {8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20};
//	protected final List<RootSeqSymmetry> rootSyms = new ArrayList<RootSeqSymmetry>();
//	protected final List<RootSeqSymmetry> graphSyms = new ArrayList<RootSeqSymmetry>();
//	protected final List<RootSeqSymmetry> annotSyms = new ArrayList<RootSeqSymmetry>();
    private JRadioButton hiddenRadioButton;

    /**
     * Creates new form TrackPreferencesGUI
     */
    public TrackPreferencesGUI() {
        hiddenRadioButton = new JRadioButton();
        initComponents();
        getClearButton().setHideActionText(true);
        getHideButton().setHideActionText(true);
        resetAll();
        getButtonGroup1().add(hiddenRadioButton);
    }

    private ColorSchemeComboBox createColorSchemeComboBox() {
        final ItemListener itemListener = new ItemListener() {

            public void itemStateChanged(ItemEvent ie) {
                switch (ie.getStateChange()) {
                    case ItemEvent.DESELECTED:
                        break;
                    case ItemEvent.SELECTED:
                        Object o = ie.getSource();
                        if (o instanceof ColorSchemeComboBox) {
                            ColorSchemeComboBox csb = (ColorSchemeComboBox) o;
                            ColorScheme s = (ColorScheme) csb.getSelectedItem();
                            ColorSchemeAction.getAction().tempAction(s);
                        }
                        break;
                    default:
                        System.err.println(
                                "SchemeChoser.$ItemListener.itemStateChanged: Unexpected state change: "
                                + ie.getStateChange());
                }
            }
        };
        ColorSchemeComboBox colorSchemeBox = new ColorSchemeComboBox() {
            private static final long serialVersionUID = 1L;

            @Override
            public void setChoices(int i) {
                this.removeItemListener(itemListener);
                super.setChoices(i);
                this.addItemListener(itemListener);
            }
        };
        colorSchemeBox.addItemListener(itemListener);
        colorSchemeBox.setChoices(0);
        return colorSchemeBox;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        graphPanel = new javax.swing.JPanel();
        graphStyleLineRadioButton = new javax.swing.JRadioButton();
        graphStyleBarRadioButton = new javax.swing.JRadioButton();
        graphStyleStairStepRadioButton = new javax.swing.JRadioButton();
        floatCheckBox = new javax.swing.JCheckBox();
        YAxisCheckBox = new javax.swing.JCheckBox();
        graphStyleHeatMapRadioButton = new javax.swing.JRadioButton();
        graphStyleDotRadioButton = new javax.swing.JRadioButton();
        graphStyleMinMaxAvgRadioButton = new javax.swing.JRadioButton();
        graphStyleHeatMapComboBox = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        labelCheckBox = new javax.swing.JCheckBox();
        stylePanel = new javax.swing.JPanel();
        labelSizeComboBox = new javax.swing.JComboBox();
        colorSchemeLabel = new javax.swing.JLabel();
        colorSchemeComboBox = createColorSchemeComboBox();
        foregroundColorComboBox = new com.jidesoft.combobox.ColorComboBox();
        backgroundColorComboBox = new com.jidesoft.combobox.ColorComboBox();
        labelColorComboBox = new com.jidesoft.combobox.ColorComboBox();
        foregroundColorLabel = new javax.swing.JLabel();
        labelColorLabel = new javax.swing.JLabel();
        backgroundColorLabel = new javax.swing.JLabel();
        labelSizeLabel = new javax.swing.JLabel();
        trackNameTextField = new javax.swing.JTextField();
        annotationsPanel = new javax.swing.JPanel();
        stackDepthLabel = new javax.swing.JLabel();
        stackDepthTextField = new JRPTextField("trackPreference_maxDepth");
        ((AbstractDocument)stackDepthTextField.getDocument()).setDocumentFilter(new NumericFilter.IntegerNumericFilter());
        labelFieldLabel = new javax.swing.JLabel();
        labelFieldComboBox = new javax.swing.JComboBox();
        strands2TracksCheckBox = new javax.swing.JCheckBox();
        strandsArrowCheckBox = new javax.swing.JCheckBox();
        strandsColorCheckBox = new javax.swing.JCheckBox();
        strandsLabel = new javax.swing.JLabel();
        strandsForwardColorLabel = new javax.swing.JLabel();
        strandsReverseColorLabel = new javax.swing.JLabel();
        strandsReverseColorComboBox = new com.jidesoft.combobox.ColorComboBox();
        strandsForwardColorComboBox = new com.jidesoft.combobox.ColorComboBox();
        stackDepthGoButton = new javax.swing.JButton();
        stackDepthAllButton = new javax.swing.JButton(com.affymetrix.igb.shared.ChangeExpandMaxOptimizeAction.getAction());
        selectAllButton = new javax.swing.JButton(com.affymetrix.igb.shared.SelectAllAction.getAction());
        hideButton = new javax.swing.JButton(com.affymetrix.igb.action.HideAction.getAction());
        clearButton = new javax.swing.JButton(com.affymetrix.igb.action.RemoveDataFromTracksAction.getAction());
        restoreToDefaultButton = new javax.swing.JButton(com.affymetrix.igb.action.RestoreToDefaultAction.getAction());

        org.jdesktop.layout.GroupLayout jFrame1Layout = new org.jdesktop.layout.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        graphPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Graph"));
        graphPanel.setPreferredSize(new java.awt.Dimension(155, 190));

        buttonGroup1.add(graphStyleLineRadioButton);
        graphStyleLineRadioButton.setText("Line");
        graphStyleLineRadioButton.setMinimumSize(new java.awt.Dimension(0, 0));
        graphStyleLineRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphStyleLineRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(graphStyleBarRadioButton);
        graphStyleBarRadioButton.setText("Bar");
        graphStyleBarRadioButton.setMinimumSize(new java.awt.Dimension(0, 0));
        graphStyleBarRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphStyleBarRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(graphStyleStairStepRadioButton);
        graphStyleStairStepRadioButton.setText("StairStep");
        graphStyleStairStepRadioButton.setMinimumSize(new java.awt.Dimension(0, 0));
        graphStyleStairStepRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphStyleStairStepRadioButtonActionPerformed(evt);
            }
        });

        floatCheckBox.setText("Float");
        floatCheckBox.setIconTextGap(2);
        floatCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        floatCheckBox.setMinimumSize(new java.awt.Dimension(0, 0));
        floatCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floatCheckBoxActionPerformed(evt);
            }
        });

        YAxisCheckBox.setText("Y-axis");
        YAxisCheckBox.setIconTextGap(2);
        YAxisCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        YAxisCheckBox.setMinimumSize(new java.awt.Dimension(0, 0));
        YAxisCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YAxisCheckBoxActionPerformed(evt);
            }
        });

        buttonGroup1.add(graphStyleHeatMapRadioButton);
        graphStyleHeatMapRadioButton.setMinimumSize(new java.awt.Dimension(0, 0));
        graphStyleHeatMapRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphStyleHeatMapRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(graphStyleDotRadioButton);
        graphStyleDotRadioButton.setText("Dot");
        graphStyleDotRadioButton.setMinimumSize(new java.awt.Dimension(0, 0));
        graphStyleDotRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphStyleDotRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(graphStyleMinMaxAvgRadioButton);
        graphStyleMinMaxAvgRadioButton.setText("Min/Max/Mean");
        graphStyleMinMaxAvgRadioButton.setMinimumSize(new java.awt.Dimension(0, 0));
        graphStyleMinMaxAvgRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphStyleMinMaxAvgRadioButtonActionPerformed(evt);
            }
        });

        graphStyleHeatMapComboBox.setModel(new DefaultComboBoxModel(com.affymetrix.genometryImpl.style.HeatMap.getStandardNames()));
        graphStyleHeatMapComboBox.setMinimumSize(new java.awt.Dimension(0, 0));
        graphStyleHeatMapComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphStyleHeatMapComboBoxActionPerformed(evt);
            }
        });

        labelCheckBox.setText("Label");
        labelCheckBox.setIconTextGap(2);
        labelCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelCheckBoxActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout graphPanelLayout = new org.jdesktop.layout.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(graphPanelLayout.createSequentialGroup()
                .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(graphPanelLayout.createSequentialGroup()
                        .add(graphStyleHeatMapRadioButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(graphStyleHeatMapComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(graphStyleMinMaxAvgRadioButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(graphPanelLayout.createSequentialGroup()
                        .add(labelCheckBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(YAxisCheckBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(floatCheckBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(graphPanelLayout.createSequentialGroup()
                            .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(graphStyleStairStepRadioButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(graphStyleLineRadioButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(graphStyleBarRadioButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(graphStyleDotRadioButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 194, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, graphPanelLayout.createSequentialGroup()
                .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(floatCheckBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(YAxisCheckBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labelCheckBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(graphStyleLineRadioButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(graphStyleBarRadioButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(graphStyleStairStepRadioButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(graphStyleDotRadioButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(graphStyleMinMaxAvgRadioButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(graphPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(graphStyleHeatMapRadioButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(graphStyleHeatMapComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        stylePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Style"));

        labelSizeComboBox.setModel(new DefaultComboBoxModel(SUPPORTED_SIZE));
        labelSizeComboBox.setMinimumSize(new java.awt.Dimension(0, 0));
        labelSizeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelSizeComboBoxActionPerformed(evt);
            }
        });

        colorSchemeLabel.setText("Scheme");

        colorSchemeComboBox.setMinimumSize(new java.awt.Dimension(0, 0));
        colorSchemeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorSchemeComboBoxActionPerformed(evt);
            }
        });

        foregroundColorComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        foregroundColorComboBox.setButtonVisible(false);
        foregroundColorComboBox.setColorValueVisible(false);
        foregroundColorComboBox.setMaximumSize(new java.awt.Dimension(150, 20));
        foregroundColorComboBox.setStretchToFit(true);
        foregroundColorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foregroundColorComboBoxActionPerformed(evt);
            }
        });

        backgroundColorComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        backgroundColorComboBox.setButtonVisible(false);
        backgroundColorComboBox.setColorValueVisible(false);
        backgroundColorComboBox.setMaximumSize(new java.awt.Dimension(150, 20));
        backgroundColorComboBox.setStretchToFit(true);
        backgroundColorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundColorComboBoxActionPerformed(evt);
            }
        });

        labelColorComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        labelColorComboBox.setButtonVisible(false);
        labelColorComboBox.setColorValueVisible(false);
        labelColorComboBox.setMaximumSize(new java.awt.Dimension(150, 20));
        labelColorComboBox.setStretchToFit(true);
        labelColorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelColorComboBoxActionPerformed(evt);
            }
        });

        foregroundColorLabel.setText("Foreground Color");

        labelColorLabel.setText("Label Color");

        backgroundColorLabel.setText("Background Color");

        labelSizeLabel.setText("Font Size");

        org.jdesktop.layout.GroupLayout stylePanelLayout = new org.jdesktop.layout.GroupLayout(stylePanel);
        stylePanel.setLayout(stylePanelLayout);
        stylePanelLayout.setHorizontalGroup(
            stylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(stylePanelLayout.createSequentialGroup()
                .add(0, 0, 0)
                .add(stylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(stylePanelLayout.createSequentialGroup()
                        .add(labelColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, 0)
                        .add(labelColorLabel))
                    .add(stylePanelLayout.createSequentialGroup()
                        .add(backgroundColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, 0)
                        .add(backgroundColorLabel))
                    .add(stylePanelLayout.createSequentialGroup()
                        .add(stylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(labelSizeLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(colorSchemeLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(stylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labelSizeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(colorSchemeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(stylePanelLayout.createSequentialGroup()
                        .add(foregroundColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, 0)
                        .add(foregroundColorLabel)))
                .addContainerGap())
        );
        stylePanelLayout.setVerticalGroup(
            stylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(stylePanelLayout.createSequentialGroup()
                .add(stylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(foregroundColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(foregroundColorLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(stylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(backgroundColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(backgroundColorLabel))
                .add(12, 12, 12)
                .add(stylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelColorLabel)
                    .add(labelColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 10, Short.MAX_VALUE)
                .add(stylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelSizeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labelSizeLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(stylePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(colorSchemeLabel)
                    .add(colorSchemeComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(16, 16, 16))
        );

        trackNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackNameTextFieldActionPerformed(evt);
            }
        });

        annotationsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Annotations"));

        stackDepthLabel.setText("Depth");

        stackDepthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stackDepthTextFieldActionPerformed(evt);
            }
        });

        labelFieldLabel.setText("Label Field");

        labelFieldComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelFieldComboBoxActionPerformed(evt);
            }
        });

        strands2TracksCheckBox.setText("2 track");
        strands2TracksCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strands2TracksCheckBoxActionPerformed(evt);
            }
        });

        strandsArrowCheckBox.setText("Arrow");
        strandsArrowCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strandsArrowCheckBoxActionPerformed(evt);
            }
        });

        strandsColorCheckBox.setText("Color:");
        strandsColorCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strandsColorCheckBoxActionPerformed(evt);
            }
        });

        strandsLabel.setText("+/- Strand Options:");

        strandsForwardColorLabel.setText("+");

        strandsReverseColorLabel.setText("-");

        strandsReverseColorComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        strandsReverseColorComboBox.setButtonVisible(false);
        strandsReverseColorComboBox.setColorValueVisible(false);
        strandsReverseColorComboBox.setMaximumSize(new java.awt.Dimension(150, 20));
        strandsReverseColorComboBox.setStretchToFit(true);
        strandsReverseColorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strandsReverseColorComboBoxActionPerformed(evt);
            }
        });

        strandsForwardColorComboBox.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        strandsForwardColorComboBox.setButtonVisible(false);
        strandsForwardColorComboBox.setColorValueVisible(false);
        strandsForwardColorComboBox.setMaximumSize(new java.awt.Dimension(150, 20));
        strandsForwardColorComboBox.setStretchToFit(true);
        strandsForwardColorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strandsForwardColorComboBoxActionPerformed(evt);
            }
        });

        stackDepthGoButton.setText("Go");
        stackDepthGoButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        stackDepthGoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stackDepthGoButtonActionPerformed(evt);
            }
        });

        stackDepthAllButton.setText("All");
        stackDepthAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stackDepthAllButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout annotationsPanelLayout = new org.jdesktop.layout.GroupLayout(annotationsPanel);
        annotationsPanel.setLayout(annotationsPanelLayout);
        annotationsPanelLayout.setHorizontalGroup(
            annotationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(annotationsPanelLayout.createSequentialGroup()
                .add(annotationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(strandsLabel)
                    .add(annotationsPanelLayout.createSequentialGroup()
                        .add(strandsColorCheckBox)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(strandsForwardColorLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(strandsForwardColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(10, 10, 10)
                        .add(strandsReverseColorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(strandsReverseColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(annotationsPanelLayout.createSequentialGroup()
                        .add(strands2TracksCheckBox)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(strandsArrowCheckBox)))
                .addContainerGap())
            .add(annotationsPanelLayout.createSequentialGroup()
                .add(labelFieldLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(labelFieldComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(annotationsPanelLayout.createSequentialGroup()
                .add(stackDepthLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(stackDepthTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(stackDepthGoButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(stackDepthAllButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        annotationsPanelLayout.setVerticalGroup(
            annotationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(annotationsPanelLayout.createSequentialGroup()
                .add(annotationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(stackDepthLabel)
                    .add(stackDepthTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(stackDepthGoButton)
                    .add(stackDepthAllButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(annotationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelFieldLabel)
                    .add(labelFieldComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(strandsLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(annotationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(strands2TracksCheckBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(strandsArrowCheckBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(annotationsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(strandsColorCheckBox)
                    .add(strandsForwardColorLabel)
                    .add(strandsForwardColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(strandsReverseColorLabel)
                    .add(strandsReverseColorComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        selectAllButton.setText("Select All");
        selectAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllButtonActionPerformed(evt);
            }
        });

        hideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideButtonActionPerformed(evt);
            }
        });

        clearButton.setMaximumSize(new java.awt.Dimension(29, 29));
        clearButton.setMinimumSize(new java.awt.Dimension(29, 29));
        clearButton.setPreferredSize(new java.awt.Dimension(29, 29));
        clearButton.setRequestFocusEnabled(false);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        restoreToDefaultButton.setText("Restore Default");
        restoreToDefaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreToDefaultButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(trackNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 256, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(selectAllButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(hideButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(clearButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(restoreToDefaultButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(stylePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(annotationsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(graphPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 208, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(selectAllButton)
                        .add(trackNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(restoreToDefaultButton)
                            .add(clearButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(hideButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(0, 0, 0)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(graphPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(annotationsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(stylePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void floatCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floatCheckBoxActionPerformed
            if (is_listening) {
                floatCheckBoxActionPerformedA(evt);
            }
	}//GEN-LAST:event_floatCheckBoxActionPerformed

	private void labelCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelCheckBoxActionPerformed
            if (is_listening) {
                labelCheckBoxActionPerformedA(evt);
            }
	}//GEN-LAST:event_labelCheckBoxActionPerformed

	private void YAxisCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YAxisCheckBoxActionPerformed
            if (is_listening) {
                YAxisCheckBoxActionPerformedA(evt);
            }
	}//GEN-LAST:event_YAxisCheckBoxActionPerformed

	private void graphStyleHeatMapComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphStyleHeatMapComboBoxActionPerformed
            if (is_listening) {
                graphStyleHeatMapComboBoxActionPerformedA(evt);
            }
	}//GEN-LAST:event_graphStyleHeatMapComboBoxActionPerformed

	private void labelSizeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelSizeComboBoxActionPerformed
            if (is_listening) {
                labelSizeComboBoxActionPerformedA(evt);
            }
	}//GEN-LAST:event_labelSizeComboBoxActionPerformed

	private void colorSchemeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorSchemeComboBoxActionPerformed
            if (is_listening) {
                colorSchemeComboBoxActionPerformedA(evt);
            }
	}//GEN-LAST:event_colorSchemeComboBoxActionPerformed

	private void labelFieldComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelFieldComboBoxActionPerformed
            if (is_listening) {
                labelFieldComboBoxActionPerformedA(evt);
            }
	}//GEN-LAST:event_labelFieldComboBoxActionPerformed

	private void strands2TracksCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strands2TracksCheckBoxActionPerformed
            if (is_listening) {
                strands2TracksCheckBoxActionPerformedA(evt);
            }
	}//GEN-LAST:event_strands2TracksCheckBoxActionPerformed

	private void strandsArrowCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strandsArrowCheckBoxActionPerformed
            if (is_listening) {
                strandsArrowCheckBoxActionPerformedA(evt);
            }
	}//GEN-LAST:event_strandsArrowCheckBoxActionPerformed

	private void strandsColorCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strandsColorCheckBoxActionPerformed
            if (is_listening) {
                strandsColorCheckBoxActionPerformedA(evt);
            }
	}//GEN-LAST:event_strandsColorCheckBoxActionPerformed

	private void labelColorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelColorComboBoxActionPerformed
            if (is_listening) {
                labelColorComboBoxActionPerformedA(evt);
            }
	}//GEN-LAST:event_labelColorComboBoxActionPerformed

	private void strandsForwardColorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strandsForwardColorComboBoxActionPerformed
            if (is_listening) {
                strandsForwardColorComboBoxActionPerformedA(evt);
            }
	}//GEN-LAST:event_strandsForwardColorComboBoxActionPerformed

	private void strandsReverseColorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strandsReverseColorComboBoxActionPerformed
            if (is_listening) {
                strandsReverseColorComboBoxActionPerformedA(evt);
            }
	}//GEN-LAST:event_strandsReverseColorComboBoxActionPerformed

	private void graphStyleLineRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphStyleLineRadioButtonActionPerformed
            if (is_listening) {
                buttonGroup1ActionPerformedA(evt);
            }
	}//GEN-LAST:event_graphStyleLineRadioButtonActionPerformed

	private void graphStyleBarRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphStyleBarRadioButtonActionPerformed
            if (is_listening) {
                buttonGroup1ActionPerformedA(evt);
            }
	}//GEN-LAST:event_graphStyleBarRadioButtonActionPerformed

	private void graphStyleStairStepRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphStyleStairStepRadioButtonActionPerformed
            if (is_listening) {
                buttonGroup1ActionPerformedA(evt);
            }
	}//GEN-LAST:event_graphStyleStairStepRadioButtonActionPerformed

	private void graphStyleDotRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphStyleDotRadioButtonActionPerformed
            if (is_listening) {
                buttonGroup1ActionPerformedA(evt);
            }
	}//GEN-LAST:event_graphStyleDotRadioButtonActionPerformed

	private void graphStyleMinMaxAvgRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphStyleMinMaxAvgRadioButtonActionPerformed
            if (is_listening) {
                buttonGroup1ActionPerformedA(evt);
            }
	}//GEN-LAST:event_graphStyleMinMaxAvgRadioButtonActionPerformed

	private void graphStyleHeatMapRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphStyleHeatMapRadioButtonActionPerformed
            if (is_listening) {
                buttonGroup1ActionPerformedA(evt);
            }
	}//GEN-LAST:event_graphStyleHeatMapRadioButtonActionPerformed

	private void backgroundColorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundColorComboBoxActionPerformed
            if (is_listening) {
                backgroundColorComboBoxActionPerformedA(evt);
            }
	}//GEN-LAST:event_backgroundColorComboBoxActionPerformed

	private void foregroundColorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foregroundColorComboBoxActionPerformed
            if (is_listening) {
                foregroundColorComboBoxActionPerformedA(evt);
            }
	}//GEN-LAST:event_foregroundColorComboBoxActionPerformed

	private void stackDepthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stackDepthTextFieldActionPerformed
            if (is_listening) {
                stackDepthTextFieldActionPerformedA(evt);
            }
	}//GEN-LAST:event_stackDepthTextFieldActionPerformed

	private void trackNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackNameTextFieldActionPerformed
            if (is_listening) {
                trackNameTextFieldActionPerformedA(evt);
            }
	}//GEN-LAST:event_trackNameTextFieldActionPerformed

	private void stackDepthGoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stackDepthGoButtonActionPerformed
            if (is_listening) {
                stackDepthGoButtonActionPerformedA(evt);
            }
	}//GEN-LAST:event_stackDepthGoButtonActionPerformed

	private void stackDepthAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stackDepthAllButtonActionPerformed
            if (is_listening) {
                stackDepthAllButtonActionPerformedA(evt);
            }
	}//GEN-LAST:event_stackDepthAllButtonActionPerformed

	private void selectAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllButtonActionPerformed
            if (is_listening) {
                selectAllButtonActionPerformedA(evt);
            }
	}//GEN-LAST:event_selectAllButtonActionPerformed

	private void hideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideButtonActionPerformed
            if (is_listening) {
                hideButtonActionPerformedA(evt);
            }
	}//GEN-LAST:event_hideButtonActionPerformed

	private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
            if (is_listening) {
                clearButtonActionPerformedA(evt);
            }
	}//GEN-LAST:event_clearButtonActionPerformed

	private void restoreToDefaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreToDefaultButtonActionPerformed
            if (is_listening) {
                restoreToDefaultButtonActionPerformedA(evt);
            }
	}//GEN-LAST:event_restoreToDefaultButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox YAxisCheckBox;
    private javax.swing.JPanel annotationsPanel;
    private com.jidesoft.combobox.ColorComboBox backgroundColorComboBox;
    private javax.swing.JLabel backgroundColorLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearButton;
    private com.affymetrix.genoviz.color.ColorSchemeComboBox colorSchemeComboBox;
    private javax.swing.JLabel colorSchemeLabel;
    private javax.swing.JCheckBox floatCheckBox;
    private com.jidesoft.combobox.ColorComboBox foregroundColorComboBox;
    private javax.swing.JLabel foregroundColorLabel;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JRadioButton graphStyleBarRadioButton;
    private javax.swing.JRadioButton graphStyleDotRadioButton;
    private javax.swing.JComboBox graphStyleHeatMapComboBox;
    private javax.swing.JRadioButton graphStyleHeatMapRadioButton;
    private javax.swing.JRadioButton graphStyleLineRadioButton;
    private javax.swing.JRadioButton graphStyleMinMaxAvgRadioButton;
    private javax.swing.JRadioButton graphStyleStairStepRadioButton;
    private javax.swing.JButton hideButton;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox labelCheckBox;
    private com.jidesoft.combobox.ColorComboBox labelColorComboBox;
    private javax.swing.JLabel labelColorLabel;
    private javax.swing.JComboBox labelFieldComboBox;
    private javax.swing.JLabel labelFieldLabel;
    private javax.swing.JComboBox labelSizeComboBox;
    private javax.swing.JLabel labelSizeLabel;
    private javax.swing.JButton restoreToDefaultButton;
    private javax.swing.JButton selectAllButton;
    private javax.swing.JButton stackDepthAllButton;
    private javax.swing.JButton stackDepthGoButton;
    private javax.swing.JLabel stackDepthLabel;
    private javax.swing.JTextField stackDepthTextField;
    private javax.swing.JCheckBox strands2TracksCheckBox;
    private javax.swing.JCheckBox strandsArrowCheckBox;
    private javax.swing.JCheckBox strandsColorCheckBox;
    private com.jidesoft.combobox.ColorComboBox strandsForwardColorComboBox;
    private javax.swing.JLabel strandsForwardColorLabel;
    private javax.swing.JLabel strandsLabel;
    private com.jidesoft.combobox.ColorComboBox strandsReverseColorComboBox;
    private javax.swing.JLabel strandsReverseColorLabel;
    private javax.swing.JPanel stylePanel;
    private javax.swing.JTextField trackNameTextField;
    // End of variables declaration//GEN-END:variables

    // getters generated by Eclipse, NetBeans balked: "Read-only block of text cannot be refactored."
    public javax.swing.JPanel getAnnotationsPanel() {
        return annotationsPanel;
    }

    public com.jidesoft.combobox.ColorComboBox getBackgroundColorComboBox() {
        return backgroundColorComboBox;
    }

    public javax.swing.JLabel getBackgroundColorLabel() {
        return backgroundColorLabel;
    }

    public com.affymetrix.genoviz.color.ColorSchemeComboBox getColorSchemeComboBox() {
        return colorSchemeComboBox;
    }

    public javax.swing.JLabel getColorSchemeLabel() {
        return colorSchemeLabel;
    }

    public javax.swing.JCheckBox getFloatCheckBox() {
        return floatCheckBox;
    }

    public javax.swing.JCheckBox getLabelCheckBox() {
        return labelCheckBox;
    }

    public com.jidesoft.combobox.ColorComboBox getForegroundColorComboBox() {
        return foregroundColorComboBox;
    }

    public javax.swing.JLabel getForegroundColorLabel() {
        return foregroundColorLabel;
    }

    public javax.swing.JPanel getGraphPanel() {
        return graphPanel;
    }

    public javax.swing.JRadioButton getGraphStyleBarRadioButton() {
        return graphStyleBarRadioButton;
    }

    public javax.swing.JRadioButton getGraphStyleDotRadioButton() {
        return graphStyleDotRadioButton;
    }

    public javax.swing.JComboBox getGraphStyleHeatMapComboBox() {
        return graphStyleHeatMapComboBox;
    }

    public javax.swing.JRadioButton getGraphStyleHeatMapRadioButton() {
        return graphStyleHeatMapRadioButton;
    }

    public javax.swing.JRadioButton getGraphStyleLineRadioButton() {
        return graphStyleLineRadioButton;
    }

    public javax.swing.JRadioButton getGraphStyleMinMaxAvgRadioButton() {
        return graphStyleMinMaxAvgRadioButton;
    }

    public javax.swing.JRadioButton getGraphStyleStairStepRadioButton() {
        return graphStyleStairStepRadioButton;
    }

    public javax.swing.JFrame getjFrame1() {
        return jFrame1;
    }

    public com.jidesoft.combobox.ColorComboBox getLabelColorComboBox() {
        return labelColorComboBox;
    }

    public javax.swing.JLabel getLabelColorLabel() {
        return labelColorLabel;
    }

    public javax.swing.JComboBox getLabelFieldComboBox() {
        return labelFieldComboBox;
    }

    public javax.swing.JLabel getLabelFieldLabel() {
        return labelFieldLabel;
    }

    public javax.swing.JComboBox getLabelSizeComboBox() {
        return labelSizeComboBox;
    }

    public javax.swing.JLabel getStackDepthLabel() {
        return stackDepthLabel;
    }

    public javax.swing.JTextField getStackDepthTextField() {
        return stackDepthTextField;
    }

    public javax.swing.JCheckBox getStrands2TracksCheckBox() {
        return strands2TracksCheckBox;
    }

    public javax.swing.JCheckBox getStrandsArrowCheckBox() {
        return strandsArrowCheckBox;
    }

    public javax.swing.JCheckBox getStrandsColorCheckBox() {
        return strandsColorCheckBox;
    }

    public com.jidesoft.combobox.ColorComboBox getStrandsForwardColorComboBox() {
        return strandsForwardColorComboBox;
    }

    public javax.swing.JLabel getStrandsForwardColorLabel() {
        return strandsForwardColorLabel;
    }

    public javax.swing.JLabel getStrandsLabel() {
        return strandsLabel;
    }

    public com.jidesoft.combobox.ColorComboBox getStrandsReverseColorComboBox() {
        return strandsReverseColorComboBox;
    }

    public javax.swing.JLabel getStrandsReverseColorLabel() {
        return strandsReverseColorLabel;
    }

    public javax.swing.JPanel getStylePanel() {
        return stylePanel;
    }

    public javax.swing.JTextField getTrackNameTextField() {
        return trackNameTextField;
    }

    public javax.swing.JCheckBox getYAxisCheckBox() {
        return YAxisCheckBox;
    }

    public final javax.swing.ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public javax.swing.JButton getClearButton() {
        return clearButton;
    }

    public javax.swing.JButton getRestoreToDefaultButton() {
        return restoreToDefaultButton;
    }

    public javax.swing.JButton getSelectAllButton() {
        return selectAllButton;
    }

    public javax.swing.JButton getHideButton() {
        return hideButton;
    }

    public javax.swing.JButton getStackDepthAllButton() {
        return stackDepthAllButton;
    }

    public javax.swing.JButton getStackDepthGoButton() {
        return stackDepthGoButton;
    }

    public javax.swing.JLabel getLabelSizeLabel() {
        return labelSizeLabel;
    }

    // you can "generate" these by copying all the event handlers
    // into your text processor and globally changing (must handle regex)
    // "ActionPerformed" to "ActionPerformedA"
    // "private" to "protected abstract"
    // "// TODO add your handling code here:" to ""
    // "                                     
    // "                                    
    protected abstract void viewModeComboBoxActionPerformedA(ActionEvent evt);

    protected abstract void floatCheckBoxActionPerformedA(ActionEvent evt);

    protected abstract void labelCheckBoxActionPerformedA(ActionEvent evt);

    protected abstract void YAxisCheckBoxActionPerformedA(ActionEvent evt);

    protected abstract void graphStyleHeatMapComboBoxActionPerformedA(ActionEvent evt);

    protected abstract void labelSizeComboBoxActionPerformedA(ActionEvent evt);

    protected abstract void colorSchemeComboBoxActionPerformedA(ActionEvent evt);

    protected abstract void labelFieldComboBoxActionPerformedA(ActionEvent evt);

    protected abstract void strands2TracksCheckBoxActionPerformedA(ActionEvent evt);

    protected abstract void strandsArrowCheckBoxActionPerformedA(ActionEvent evt);

    protected abstract void strandsColorCheckBoxActionPerformedA(ActionEvent evt);

    protected abstract void labelColorComboBoxActionPerformedA(ActionEvent evt);

    protected abstract void strandsForwardColorComboBoxActionPerformedA(ActionEvent evt);

    protected abstract void strandsReverseColorComboBoxActionPerformedA(ActionEvent evt);

    protected abstract void buttonGroup1ActionPerformedA(ActionEvent evt);

    protected abstract void backgroundColorComboBoxActionPerformedA(ActionEvent evt);

    protected abstract void foregroundColorComboBoxActionPerformedA(ActionEvent evt);

    protected abstract void stackDepthTextFieldActionPerformedA(ActionEvent evt);

    protected abstract void trackNameTextFieldActionPerformedA(ActionEvent evt);

    protected abstract void stackDepthGoButtonActionPerformedA(ActionEvent evt);

    protected abstract void stackDepthAllButtonActionPerformedA(ActionEvent evt);

    protected abstract void selectAllButtonActionPerformedA(ActionEvent evt);

    protected abstract void hideButtonActionPerformedA(ActionEvent evt);

    protected abstract void clearButtonActionPerformedA(ActionEvent evt);

    protected abstract void restoreToDefaultButtonActionPerformedA(ActionEvent evt);

	// you can "generate" these by copying all the event handlers
    // into your text processor and globally changing (must handle regex)
    // "ActionPerformed" to "Reset"
    // "private" to "protected abstract"
    // "java.awt.event.ActionEvent evt" to ""
    // "// TODO add your handling code here:" to ""
	// "//GEN-FIRST:event_[a-zA-Z0-9]*" to ""
	// "//GEN-LAST:event_[a-zA-Z0-9]*" to ""
    protected abstract void floatCheckBoxReset();

    protected abstract void labelCheckBoxReset();

    protected abstract void YAxisCheckBoxReset();

    protected abstract void graphStyleHeatMapComboBoxReset();

    protected abstract void labelSizeComboBoxReset();

    protected abstract void colorSchemeComboBoxReset();

    protected abstract void labelFieldComboBoxReset();

    protected abstract void strandsLabelReset();

    protected abstract void strands2TracksCheckBoxReset();

    protected abstract void strandsArrowCheckBoxReset();

    protected abstract void strandsColorCheckBoxReset();

    protected abstract void labelColorComboBoxReset();

    protected abstract void strandsForwardColorComboBoxReset();

    protected abstract void strandsReverseColorComboBoxReset();

    protected abstract void buttonGroup1Reset();

    protected abstract void backgroundColorComboBoxReset();

    protected abstract void foregroundColorComboBoxReset();

    protected abstract void stackDepthTextFieldReset();

    protected abstract void trackNameTextFieldReset();

    protected abstract void stackDepthGoButtonReset();

    protected abstract void stackDepthAllButtonReset();

    protected abstract void selectAllButtonReset();

    protected abstract void hideButtonReset();

    protected abstract void clearButtonReset();

    protected abstract void restoreToDefaultButtonReset();

    protected final void resetAll() {
        is_listening = false;
        getStylePanel().setEnabled(allStyles.size() > 0);
        getAnnotationsPanel().setEnabled(annotStyles.size() > 0);
        getGraphPanel().setEnabled(graphStates.size() > 0);
        floatCheckBoxReset();
        labelCheckBoxReset();
        YAxisCheckBoxReset();
        graphStyleHeatMapComboBoxReset();
        labelSizeComboBoxReset();
        colorSchemeComboBoxReset();
        labelFieldComboBoxReset();
        strandsLabelReset();
        strands2TracksCheckBoxReset();
        strandsArrowCheckBoxReset();
        strandsColorCheckBoxReset();
        labelColorComboBoxReset();
        strandsForwardColorComboBoxReset();
        strandsReverseColorComboBoxReset();
        buttonGroup1Reset();
        backgroundColorComboBoxReset();
        foregroundColorComboBoxReset();
        stackDepthTextFieldReset();
        trackNameTextFieldReset();
        stackDepthGoButtonReset();
        stackDepthAllButtonReset();
        selectAllButtonReset();
        hideButtonReset();
        clearButtonReset();
        restoreToDefaultButtonReset();
        is_listening = true;
    }

    protected void unselectGraphStyle() {
        hiddenRadioButton.setSelected(true); // deselect all visible radio buttons
    }
}
