/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWorkspaceManager2.java
 *
 * Created on Nov 9, 2011, 2:54:08 PM
 */
package com.affymetrix.igb.view.load;

import com.affymetrix.igb.view.SeqMapView;
import com.affymetrix.igb.IGBConstants;
import com.affymetrix.igb.view.SeqGroupView;
import java.awt.CardLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import be.pwnt.jflow.JFlowPanel;
import be.pwnt.jflow.event.ShapeEvent;
import be.pwnt.jflow.event.ShapeListener;
import com.affymetrix.common.CommonUtils;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 * 
 * This JPanel composes the welcome page.  The bottom panel is filled with a 
 * CoverFlow class.
 * 
 * @author jfvillal
 */
public class WelcomePage extends javax.swing.JPanel {
	
	
	/** Creates new form MainWorkspaceManager2 */
	public WelcomePage( JPanel cover_flow) {
		initComponents();
		CoverFlowPane.setLayout( new BorderLayout());
		CoverFlowPane.add( cover_flow );
		URL url = CommonUtils.class.getClassLoader().getResource("welcome.html");
		WelcomePane.setContentType("text/html");
		try {
			WelcomePane.setText( getContent(this, url.openStream()));
		} catch (IOException ex) {
			Logger.getLogger(WelcomePage.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	
	 public static String getContent( JPanel context, InputStream resource){
        
        BufferedReader stream = new BufferedReader( 
                                        new InputStreamReader( 
                                            new DataInputStream(  
                                                    resource
                                            ) 
                                        )
        );
        
        String content = "";
        String line = "";
        try {
            while( (line = stream.readLine() ) != null){
                content += line + "\n";
            }
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        return content;
    }
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CoverFlowPane = new javax.swing.JPanel();
        WelcomePane = new javax.swing.JEditorPane();

        setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout CoverFlowPaneLayout = new javax.swing.GroupLayout(CoverFlowPane);
        CoverFlowPane.setLayout(CoverFlowPaneLayout);
        CoverFlowPaneLayout.setHorizontalGroup(
            CoverFlowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );
        CoverFlowPaneLayout.setVerticalGroup(
            CoverFlowPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );

        WelcomePane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        WelcomePane.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(WelcomePane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                    .addComponent(CoverFlowPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomePane, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CoverFlowPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CoverFlowPane;
    private javax.swing.JEditorPane WelcomePane;
    // End of variables declaration//GEN-END:variables


}
