/*
 * KeyStrokesViewGUI.java
 *
 * Created on Jan 19, 2012, 10:11:49 AM
 */
package com.lorainelab.igb.keystrokes.form;

import aQute.bnd.annotation.component.Activate;
import aQute.bnd.annotation.component.Component;
import aQute.bnd.annotation.component.Reference;
import com.lorainelab.igb.keystrokes.KeyStrokesView;
import com.lorainelab.igb.services.window.preferences.PreferencesPanelProvider;
import com.lorainelab.igb.services.window.preferences.IPrefEditorComponent;
import javax.swing.JPanel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author lorainelab
 */
@Component(name = KeyStrokesViewGUI.COMPONENT_NAME, immediate = true, provide = PreferencesPanelProvider.class)
public class KeyStrokesViewGUI extends IPrefEditorComponent implements PreferencesPanelProvider {

    public static final String COMPONENT_NAME = "KeyStrokesViewGUI";
    private static final Logger logger = LoggerFactory.getLogger(KeyStrokesViewGUI.class);
    private static final long serialVersionUID = 1L;

    private KeyStrokesView ksv;

    /**
     * Creates new form KeyStrokesViewGUI
     */
    public KeyStrokesViewGUI() {
        this.setName("Toolbar");
        this.setToolTipText("Edit Locations");
    }

    @Activate
    public void activate() {        
        initComponents();
    }

    @Reference (optional = false)
    public void setKsv(KeyStrokesView ksv) {
        this.ksv = ksv;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = ksv.table;
        jLabel1 = ksv.edit_panel.note_label;

        jTable1.setModel(ksv.table.getModel());
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .add(jLabel1)
                .add(82, 82, 82))
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refresh() {
        ksv.invokeRefreshTable();
    }

    @Override
    public int getTabWeight() {
        return 1;
    }

    @Override
    public JPanel getPanel() {
        return this;
    }

}
