/**
*   Copyright (c) 1998-2008 Affymetrix, Inc.
*
*   Licensed under the Common Public License, Version 1.0 (the "License").
*   A copy of the license must be included with any distribution of
*   this source code.
*   Distributions from Affymetrix, Inc., place this in the
*   IGB_LICENSE.html file.
*
*   The license is also available at
*   http://www.opensource.org/licenses/cpl.php
*/

package com.affymetrix.genoviz.event;

import java.awt.*;
import com.affymetrix.genoviz.bioviews.RubberBand;
import java.awt.event.MouseEvent;

/**
 *  Event generated by Neo* widgets when rubberbanding is enabled, to
 *  notify listeners of rubber band start, stop, and end.
 *  Propogated to event listeners via JDK1.0-compatible delegation-based
 *  event handling (pseudo-1.1 event handling)
 */
public class NeoRubberBandEvent extends MouseEvent  {
  static final long serialVersionUID = 1L;

  /** The event IDs for different types of band events. */
  public static final int BAND_START = AWTEvent.RESERVED_ID_MAX;
  public static final int BAND_STRETCH = BAND_START + 1;
  public static final int BAND_END = BAND_START + 2;

  final protected RubberBand rband;

  public NeoRubberBandEvent(MouseEvent evt, int id, RubberBand rb) {
    this((Component)evt.getSource(), id, evt.getWhen(), evt.getModifiers(),
        evt.getX(), evt.getY(), evt.getClickCount(), evt.isPopupTrigger(), rb);
  }

  public NeoRubberBandEvent(Component source, int id, long when,
      int modifiers, int x, int y, int clickCount,
      boolean popupTrigger, RubberBand rb) {
    super(source, id, when, modifiers, x, y, clickCount, popupTrigger);
    this.rband = rb;
  }

  public Rectangle getPixelBox() {
    return rband.getBoundingBox();
  }

  public RubberBand getRubberBand() {
    return rband;
  }

  /** @return true if {@link #getID()} equals {@link #BAND_START}. */
  public boolean isRubberBandStart() {
    return getID() == BAND_START;
  }
  
  /** @return true if {@link #getID()} equals {@link #BAND_END}. */
  public boolean isRubberBandEnd() {
    return getID() == BAND_END;
  }
  
  /** @return true if {@link #getID()} equals {@link #BAND_STRETCH}. */
  public boolean isRubberBandStretch() {
    return getID() == BAND_STRETCH;
  }
}
